app_version: 0.78.0
capabilities: []
categories:
- media
changelog_url: https://github.com/bayang/jelu/releases
date_added: '2025-01-08'
description: Jelu is a self hosted read and to-read list book tracker
home: https://github.com/bayang/jelu
host_mounts: []
icon: https://media.sys.truenas.net/apps/jelu/icons/icon.png
keywords:
- media
- book
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jelu
run_as_context:
- description: Container [jelu] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/jelu/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/jelu/screenshots/screenshot2.png
sources:
- https://github.com/bayang/jelu
- https://hub.docker.com/repository/docker/wabayang/jelu
title: Jelu
train: community
version: 1.1.0
