app_version: 3.8.1
capabilities: []
categories:
- media
changelog_url: https://github.com/kiwix/kiwix-tools/releases
date_added: '2025-08-04'
description: Kiwix Server is a ZIM compatible Web server.
home: https://github.com/kiwix/kiwix-tools
host_mounts: []
icon: https://media.sys.truenas.net/apps/kiwix-server/icons/icon.svg
keywords:
- kiwix
- server
- zim
- wiki
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kiwix-server
run_as_context:
- description: Container [kiwix-server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/kiwix/kiwix-tools
title: Kiwix Server
train: community
version: 1.1.1
