annotations:
  min_scale_version: 24.10.2.2
app_version: latest
capabilities: []
categories:
- productivity
date_added: '2024-08-02'
description: Briefkasten is a self hosted bookmarking app
home: https://github.com/ndom91/briefkasten
host_mounts: []
icon: https://media.sys.truenas.net/apps/briefkasten/icons/icon.svg
keywords:
- bookmark
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: briefkasten
run_as_context:
- description: Container [briefkasten] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/briefkasten/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/briefkasten/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/briefkasten/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/briefkasten/screenshots/screenshot4.png
sources:
- https://github.com/ndom91/briefkasten
- https://docs.briefkastenhq.com/
title: Briefkasten
train: community
version: 1.5.1
