annotations:
  min_scale_version: 24.10.2.2
app_version: tshock-1.4.4.9-5.2.4
capabilities: []
categories:
- games
changelog_url: https://github.com/ryansheehan/terraria/releases
date_added: '2024-09-17'
description: Terraria is a land of adventure! A land of mystery! A land that's yours
  to shape, defend, and enjoy.
home: https://terraria.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/terraria/icons/icon.png
keywords:
- adventure
- building
- game
- terraria
- world
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: terraria
run_as_context:
- description: Container [terraria] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://terraria.org/
- https://github.com/ryansheehan/terraria
title: Terraria
train: community
version: 1.3.1
