app_version: 12.7.1
capabilities: []
categories:
- productivity
changelog_url: https://code.forgejo.org/forgejo/runner/releases
date_added: '2025-08-22'
description: A runner for Forgejo.
home: https://forgejo.org/
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/forgejo-runner/icons/icon.svg
keywords:
- forgejo
- actions
- runner
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: forgejo-runner
run_as_context:
- description: Container [forgejo-runner] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://forgejo.org/docs/latest/admin/actions/runner-installation/
- https://code.forgejo.org/forgejo/runner
title: Forgejo Runner
train: community
version: 1.1.4
