annotations:
  min_scale_version: 24.10.2.2
app_version: 19.0-20260217
capabilities: []
categories:
- productivity
changelog_url: https://www.odoo.com/documentation/18.0/developer/reference/backend/orm/changelog.html
date_added: '2024-09-23'
description: Odoo is a suite of web based open source business apps.
home: https://www.odoo.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/odoo/icons/icon.png
keywords:
- erp
- odoo
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: odoo
run_as_context:
- description: Container [odoo] runs as non-root user and group.
  gid: 101
  group_name: Host group is [systemd-timesync]
  uid: 100
  user_name: Host user is [_apt]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/odoo/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/odoo/screenshots/screenshot2.png
sources:
- https://hub.docker.com/_/odoo
- https://github.com/odoo/odoo
title: Odoo
train: community
version: 1.5.0
