annotations:
  min_scale_version: 24.10.2.2
app_version: v0.39.0
capabilities: []
categories:
- storage
changelog_url: https://github.com/ipfs/kubo/releases
date_added: '2024-08-01'
description: Interplanetary Filesystem - the Web3 standard for content-addressing,
  interoperable with HTTP
home: https://ipfs.tech/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ipfs/icons/icon.png
keywords:
- storage
- ipfs
- file-sharing
- kubo
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ipfs
run_as_context:
- description: Container [ipfs] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/ipfs/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/ipfs/screenshots/screenshot2.png
sources:
- https://github.com/ipfs/kubo
- https://ipfs.tech/
title: IPFS
train: community
version: 1.3.2
