annotations:
  min_scale_version: 24.10.2.2
app_version: v26.02.1
capabilities:
- description: Handbrake is able to change file ownership arbitrarily
  name: CHOWN
- description: Handbrake is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Handbrake is able to bypass permission checks for file operations
  name: FOWNER
- description: Handbrake is able to send signals to any process
  name: KILL
- description: Handbrake is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Handbrake is able to change group ID of processes
  name: SETGID
- description: Handbrake is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/jlesage/docker-handbrake/releases
date_added: '2024-08-02'
description: HandBrake is a tool for converting video from nearly any format to a
  selection of modern, widely supported codecs.
home: https://github.com/jlesage/docker-handbrake
host_mounts: []
icon: https://media.sys.truenas.net/apps/handbrake/icons/icon.png
keywords:
- media
- video
- transcoder
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: handbrake
run_as_context:
- description: Container [handbrake] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/jlesage/docker-handbrake
- https://hub.docker.com/r/jlesage/handbrake
title: Handbrake
train: community
version: 2.3.2
