app_version: v2.3.0
capabilities: []
categories:
- authentication
changelog_url: https://github.com/pocket-id/pocket-id/releases
date_added: '2025-07-04'
description: Pocket ID is a simple and easy-to-use OIDC provider that allows users
  to authenticate with their passkeys to your services.
home: https://pocket-id.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/pocket-id/icons/icon.png
keywords:
- authentication
- oidc
- passkeys
- openid
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: pocket-id
run_as_context:
- description: Container [pocket-id] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/pocket-id/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/pocket-id/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/pocket-id/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/pocket-id/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/pocket-id/screenshots/screenshot5.png
sources:
- https://github.com/pocket-id/pocket-id
title: Pocket ID
train: community
version: 1.1.3
