annotations:
  min_scale_version: 24.10.2.2
app_version: v1.7.14
capabilities:
- description: Gaseous Server is able to change file ownership arbitrarily
  name: CHOWN
- description: Gaseous Server is able to change group ID of processes
  name: SETGID
- description: Gaseous Server is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://github.com/gaseous-project/gaseous-server/releases
date_added: '2024-11-15'
description: This is the server for the Gaseous system. It offers ROM and title management,
  as well as some basic in browser emulation of those ROMs.
home: https://github.com/gaseous-project/gaseous-server
host_mounts: []
icon: https://media.sys.truenas.net/apps/gaseous-server/icons/icon.png
keywords:
- games
- emulation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gaseous-server
run_as_context:
- description: Container [gaseous-server] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/gaseous-server/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/gaseous-server/screenshots/screenshot2.png
sources:
- https://github.com/gaseous-project/gaseous-server
title: Gaseous Server
train: community
version: 1.3.0
