annotations:
  min_scale_version: 24.10.2.2
app_version: 0.60.3
capabilities: []
categories:
- media
changelog_url: https://github.com/navidrome/navidrome/releases
date_added: '2024-08-02'
description: Navidrome is a personal streaming service
home: https://www.navidrome.org
host_mounts:
- description: Sound device. Only when local playback is enabled.
  host_path: /dev/snd
icon: https://media.sys.truenas.net/apps/navidrome/icons/icon.svg
keywords:
- media
- music
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: navidrome
run_as_context:
- description: Container [navidrome] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/navidrome/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/deluan/navidrome
- https://github.com/navidrome/navidrome/
title: Navidrome
train: community
version: 1.3.1
