app_version: 25.12.6
capabilities: []
categories:
- productivity
changelog_url: https://github.com/BookStackApp/BookStack/releases
date_added: '2025-06-27'
description: BookStack is a simple, self-hosted, easy-to-use platform for organizing
  and storing information
home: https://www.bookstackapp.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bookstack/icons/icon.png
keywords:
- bookstack
- documentation
- wiki
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bookstack
run_as_context:
- description: Container [bookstack] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/solidnerd/docker-bookstack
- https://hub.docker.com/r/solidnerd/bookstack
title: BookStack
train: community
version: 1.1.4
