annotations:
  min_scale_version: 24.10.2.2
app_version: 17.8-bookworm
capabilities: []
categories:
- database
changelog_url: https://www.postgresql.org/docs/release/
date_added: '2024-11-04'
description: The PostgreSQL object-relational database system provides reliability
  and data integrity.
home: https://www.postgresql.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/postgres/icons/icon.png
keywords:
- database
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: postgres
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://hub.docker.com/_/postgres
title: Postgres
train: community
version: 1.4.1
