annotations:
  min_scale_version: 24.10.2.2
app_version: latest
capabilities: []
categories:
- productivity
changelog_url: https://docs.logseq.com/#/page/changelog
date_added: '2024-08-02'
description: Logseq is a privacy-first, open-source platform for knowledge management
  and collaboration.
home: https://logseq.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/logseq/icons/icon.png
keywords:
- knowledge
- management
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: logseq
run_as_context:
- description: Container [logseq] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/logseq/logseq
title: Logseq
train: community
version: 1.3.2
