app_version: 1.11.6
capabilities:
- description: Octoprint is able to change group ID of processes
  name: SETGID
- description: Octoprint is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://octoprint.org/blog/
date_added: '2025-01-31'
description: Octoprint provides a snappy web interface for controlling consumer 3D
  printers.
home: https://octoprint.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/octoprint/icons/icon.png
keywords:
- 3D
- printer
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: octoprint
run_as_context:
- description: Container [octoprint] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/octoprint/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/octoprint/octoprint
- https://github.com/OctoPrint/OctoPrint
title: Octoprint
train: community
version: 1.1.1
