annotations:
  min_scale_version: 24.10.2.2
app_version: 0.7.6-nbxyz4
capabilities:
- description: Netboot is able to change file ownership arbitrarily
  name: CHOWN
- description: Netboot is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Netboot is able to bypass permission checks for file operations
  name: FOWNER
- description: Netboot is able to send signals to any process
  name: KILL
- description: Netboot is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Netboot is able to change group ID of processes
  name: SETGID
- description: Netboot is able to change user ID of processes
  name: SETUID
- description: Netboot is able to use chroot() system call
  name: SYS_CHROOT
categories:
- networking
changelog_url: https://github.com/netbootxyz/docker-netbootxyz/tags
date_added: '2024-08-02'
description: netboot.xyz lets you PXE boot various operating system installers or
  utilities from a single tool over the network.
home: https://netboot.xyz
host_mounts: []
icon: https://media.sys.truenas.net/apps/netbootxyz/icons/icon.png
keywords:
- tftp
- network
- pxe
- netboot
- netbootxyz
- netboot.xyz
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: netbootxyz
run_as_context:
- description: Container [netboot] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/netbootxyz/screenshots/screenshot1.jpg
sources:
- https://github.com/netbootxyz/docker-netbootxyz
- https://netboot.xyz
title: Netboot.xyz
train: community
version: 1.3.1
