app_version: hardcover-v0.4.20.129
capabilities:
- description: Bookshelf is able to change file ownership arbitrarily
  name: CHOWN
- description: Bookshelf is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Bookshelf is able to bypass permission checks for file operations
  name: FOWNER
- description: Bookshelf is able to change group ID of processes
  name: SETGID
- description: Bookshelf is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: ''
date_added: '2026-01-09'
description: A place for your books. users.
home: https://github.com/pennydreadful/bookshelf
host_mounts: []
icon: https://media.sys.truenas.net/apps/bookshelf/icons/icon.png
keywords:
- media
- ebook
- audiobook
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bookshelf
run_as_context:
- description: Container [bookshelf] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/bookshelf/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/bookshelf/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/bookshelf/screenshots/screenshot3.png
sources:
- https://github.com/pennydreadful/bookshelf
title: Bookshelf
train: community
version: 1.1.2
