annotations:
  min_scale_version: 24.10.2.2
app_version: 2.4.66
capabilities: []
categories:
- storage
date_added: '2024-08-27'
description: WebDAV is a set of extensions to the HTTP protocol which allows users
  to collaboratively edit and manage files on remote web servers.
home: http://www.webdav.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/webdav/icons/icon.png
keywords:
- webdav
- file-sharing
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: webdav
run_as_context:
- description: Container [webdav] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- http://www.webdav.org/
title: WebDAV
train: community
version: 1.3.2
