annotations:
  min_scale_version: 24.10.2.2
app_version: '9.12'
capabilities:
- description: pgAdmin is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- productivity
changelog_url: https://www.pgadmin.org/news/
date_added: '2024-09-24'
description: pgAdmin is the most popular and feature rich Open Source administration
  and development platform for PostgreSQL
home: https://www.pgadmin.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/pgadmin/icons/icon.png
keywords:
- database
- management
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: pgadmin
run_as_context:
- description: Container [pgadmin] runs as non-root user and group.
  gid: 5050
  group_name: Host group is [unknown (5050)]
  uid: 5050
  user_name: Host user is [unknown (5050)]
screenshots:
- https://media.sys.truenas.net/apps/pgadmin/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/pgadmin/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/pgadmin/screenshots/screenshot3.png
sources:
- https://hub.docker.com/r/dpage/pgadmin4
- https://www.pgadmin.org/
title: pgAdmin
train: community
version: 1.3.2
