app_version: v1.12.11
capabilities: []
categories:
- productivity
changelog_url: https://github.com/element-hq/element-web/releases
date_added: '2025-08-14'
description: Element-Web is a glossy Matrix collaboration client for the web.
home: https://element.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/element-web/icons/icon.svg
keywords:
- chat
- element
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: element-web
run_as_context:
- description: Container [element-web] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/element-hq/element-web
title: Element Web
train: community
version: 1.1.3
