app_version: 3.0.33
capabilities: []
categories:
- ai
changelog_url: https://github.com/ServiceStack/llms/releases
date_added: '2026-01-28'
description: A lightweight OpenAI-compatible gateway for multiple LLM providers with
  web UI and analytics dashboard.
home: https://llmspy.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/llmspy/icons/icon.svg
keywords:
- ai
- llm
- gateway
- openai
- api
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: llmspy
run_as_context:
- description: Container [llmspy] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots:
- https://media.sys.truenas.net/apps/llmspy/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/llmspy/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/llmspy/screenshots/screenshot3.png
sources:
- https://github.com/ServiceStack/llms
title: llms.py
train: community
version: 1.1.1
