annotations:
  min_scale_version: 24.10.2.2
app_version: 0.17.0
capabilities:
- description: Frigate is able to change file ownership arbitrarily
  name: CHOWN
- description: Frigate is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Frigate is able to bypass permission checks for file operations
  name: FOWNER
- description: Frigate is able to send signals to any process
  name: KILL
- description: Frigate is able to access performance monitoring interfaces
  name: PERFMON
- description: Frigate is able to change group ID of processes
  name: SETGID
- description: Frigate is able to change user ID of processes
  name: SETUID
categories:
- security
changelog_url: https://github.com/blakeblackshear/frigate/releases
date_added: '2024-09-12'
description: Frigate is an NVR With Realtime Object Detection for IP Cameras
home: https://frigate.video/
host_mounts: []
icon: https://media.sys.truenas.net/apps/frigate/icons/icon.svg
keywords:
- camera
- nvr
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: frigate
run_as_context:
- description: Container [frigate] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/frigate/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/frigate/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/frigate/screenshots/screenshot3.png
sources:
- https://github.com/blakeblackshear/frigate
title: Frigate
train: community
version: 1.3.3
