app_version: 1.12.1
capabilities: []
categories:
- networking
changelog_url: https://github.com/3proxy/3proxy/releases
date_added: '2025-08-13'
description: 3proxy is a powerful and lightweight HTTP/SOCKS proxy server.
home: https://github.com/3proxy/3proxy
host_mounts: []
icon: https://media.sys.truenas.net/apps/three-proxy/icons/icon.webp
keywords:
- 3proxy
- http
- socks
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: three-proxy
run_as_context:
- description: Container [3proxy] runs as non-root user and group.
  gid: 10001
  group_name: Host group is [unknown (10001)]
  uid: 10001
  user_name: Host user is [unknown (10001)]
screenshots: []
sources:
- https://github.com/3proxy/3proxy/
- https://github.com/tarampampam/3proxy-docker
title: 3proxy
train: community
version: 1.1.0
