annotations:
  min_scale_version: 24.10.2.2
app_version: v2.61.0
capabilities: []
categories:
- storage
changelog_url: https://github.com/filebrowser/filebrowser/releases
date_added: '2024-08-02'
description: File Browser provides a file managing interface within a specified directory
  and it can be used to upload, delete, preview, rename and edit your files.
home: https://filebrowser.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/filebrowser/icons/icon.png
keywords:
- files
- browser
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: filebrowser
run_as_context:
- description: Container [filebrowser] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/filebrowser/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/filebrowser/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/filebrowser/screenshots/screenshot3.png
sources:
- https://github.com/filebrowser/filebrowser
- https://hub.docker.com/r/filebrowser/filebrowser
title: File Browser
train: community
version: 1.4.4
