app_version: 5.12.28-o
capabilities:
- description: Invoice Ninja, Scheduler, Worker are able to change file ownership
    arbitrarily
  name: CHOWN
- description: Invoice Ninja, Scheduler, Worker are able to bypass file permission
    checks
  name: DAC_OVERRIDE
- description: Invoice Ninja, Scheduler, Worker are able to bypass permission checks
    for file operations
  name: FOWNER
- description: Invoice Ninja, Scheduler, Worker are able to bind to privileged ports
    (< 1024)
  name: NET_BIND_SERVICE
- description: Invoice Ninja, Scheduler, Worker are able to change group ID of processes
  name: SETGID
- description: Invoice Ninja, Scheduler, Worker are able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/invoiceninja/dockerfiles/releases
date_added: '2025-01-09'
description: Invoices, Expenses and Tasks built with Laravel, Flutter and React
home: https://invoiceninja.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/invoice-ninja/icons/icon.png
keywords:
- finance
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: invoice-ninja
run_as_context:
- description: Container [invoice-ninja] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [scheduler] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [worker] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/invoiceninja/dockerfiles
- https://hub.docker.com/r/invoiceninja/invoiceninja-octane
title: Invoice Ninja
train: community
version: 1.1.0
