app_version: v1.12.1
capabilities:
- description: Pterodactyl is able to change file ownership arbitrarily
  name: CHOWN
- description: Pterodactyl is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Pterodactyl is able to bypass permission checks for file operations
  name: FOWNER
- description: Pterodactyl is able to change group ID of processes
  name: SETGID
- description: Pterodactyl is able to change user ID of processes
  name: SETUID
categories:
- games
date_added: '2025-05-16'
description: Pterodactyl is a free, open-source game server management panel built
  with PHP, React, and Go. Designed with security in mind, Pterodactyl runs all game
  servers in isolated Docker containers while exposing a beautiful and intuitive UI
  to end users.
home: https://pterodactyl.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/pterodactyl-panel/icons/icon.svg
keywords:
- pterodactyl
- games
- servers
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: pterodactyl-panel
run_as_context:
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [pterodactyl] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/pterodactyl/panel
title: Pterodactyl Panel
train: community
version: 1.2.1
