app_version: 0.0.20
capabilities: []
categories:
- games
changelog_url: https://github.com/EditMySave/HyOS/commits/main/
date_added: '2026-02-27'
description: Hytale dedicated game server with web management UI, OAuth authentication,
  auto-updates, mod support, and REST API for server control.
home: https://hytale.com
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/hyos/icons/icon.png
keywords:
- hytale
- game-server
- voxel
- sandbox
lib_version: 2.2.6
lib_version_hash: 481cac7a3f4a590dd8e48f8497a0c10169691bc85186cf022e0e6192436e78eb
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: hyos
run_as_context:
- description: Container [manager] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/hyos/screenshots/screenshot1.png
sources:
- https://hyos.io/
- https://github.com/editmysave/hyos
- https://github.com/editmysave/hyos/pkgs/container/hyos%2Fserver
title: HyOS - Hytale Server
train: community
version: 1.0.0
