annotations:
  min_scale_version: 24.10.2.2
app_version: 2.9.0
capabilities: []
categories:
- productivity
changelog_url: https://docs.n8n.io/release-notes/
date_added: '2024-08-08'
description: n8n is an extendable workflow automation tool.
home: https://n8n.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/n8n/icons/icon.png
keywords:
- workflows
- automation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: n8n
run_as_context:
- description: Container [n8n] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [task-runner] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/n8n/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/n8n/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/n8n/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/n8n/screenshots/screenshot4.png
sources:
- https://github.com/n8n-io/n8n
- https://ghcr.io/n8n-io/n8n
title: n8n
train: community
version: 1.9.0
