app_version: v6.25.0
capabilities: []
categories:
- financial
changelog_url: https://github.com/xmrig/xmrig/blob/master/CHANGELOG.md
date_added: '2026-02-19'
description: A high performance, open source CPU/GPU miner.
home: https://xmrig.com
host_mounts:
- description: Hugepages device
  host_path: /dev/hugepages
- description: CPU device
  host_path: /dev/cpu
icon: https://media.sys.truenas.net/apps/xmrig/icons/icon.svg
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
- mining
lib_version: 2.2.3
lib_version_hash: b7b238e55723a15b606359bccee08d5b096f0fe93dffe876ea873e5a70b3d3a4
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: xmrig
run_as_context:
- description: Container [xmrig] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://xmrig.com
- https://github.com/xmrig/xmrig
- https://github.com/MAGICGrants/xmrig-docker
title: XMRig
train: community
version: 1.0.1
