annotations:
  min_scale_version: 24.10.2.2
app_version: 1.3.0
capabilities: []
categories:
- custom
date_added: '2024-09-10'
description: An application for deploying simple containers.
home: https://www.truenas.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-app/icons/icon.webp
keywords: []
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ix-app
run_as_context: []
screenshots: []
sources: []
title: iX App
train: stable
version: 1.3.1
