annotations:
  min_scale_version: 24.10.2.2
app_version: 10.0.162-mongo8
capabilities: []
categories:
- networking
changelog_url: https://github.com/goofball222/unifi/releases
date_added: '2024-08-01'
description: Unifi Controller is a network management controller for Unifi Equipment.
home: https://github.com/goofball222/unifi
host_mounts: []
icon: https://media.sys.truenas.net/apps/unifi-controller/icons/icon.png
keywords:
- controller
- unifi
- network
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: unifi-controller
run_as_context:
- description: Container [unifi] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/goofball222/unifi
title: Unifi Controller
train: community
version: 2.1.0
