app_version: 0.14.5
capabilities: []
categories:
- media
changelog_url: https://github.com/Unpackerr/unpackerr/releases
date_added: '2025-06-19'
description: Extracts downloads for Radarr, Sonarr, Lidarr, Readarr, and/or a Watch
  folder - Deletes extracted files after import
home: https://unpackerr.zip/
host_mounts: []
icon: https://media.sys.truenas.net/apps/unpackerr/icons/icon.png
keywords:
- media
- downloads
- unpack
- extraction
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: unpackerr
run_as_context:
- description: Container [unpackerr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Unpackerr/unpackerr
title: Unpackerr
train: community
version: 1.1.2
