app_version: 2.10-SNAPSHOT-ocr
capabilities: []
categories:
- productivity
changelog_url: https://fscrawler.readthedocs.io/en/latest/release/index.html
date_added: '2024-08-06'
description: FSCrawler is a crawler that helps to index binary documents such as PDF,
  Open Office, MS Office.
home: https://fscrawler.readthedocs.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/fscrawler/icons/icon.svg
keywords:
- index
- crawler
lib_version: 2.2.6
lib_version_hash: 481cac7a3f4a590dd8e48f8497a0c10169691bc85186cf022e0e6192436e78eb
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: fscrawler
run_as_context:
- description: Container [elastic-search] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [fscrawler] runs as non-root user and group.
  gid: 10001
  group_name: Host group is [unknown (10001)]
  uid: 10001
  user_name: Host user is [unknown (10001)]
screenshots: []
sources:
- https://github.com/dadoonet/fscrawler
- https://hub.docker.com/r/dadoonet/fscrawler
- https://fscrawler.readthedocs.io/
title: FSCrawler
train: community
version: 2.0.0
