app_version: 2.5.x
capabilities:
- description: Urbackup Server is able to change file ownership arbitrarily
  name: CHOWN
- description: Urbackup Server is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Urbackup Server is able to bypass permission checks for file operations
  name: FOWNER
- description: Urbackup Server is able to change group ID of processes
  name: SETGID
- description: Urbackup Server is able to change user ID of processes
  name: SETUID
categories:
- backup
date_added: '2025-01-28'
description: UrBackup is an easy to setup Open Source client/server backup system,
  that through a combination of image and file backups accomplishes both data safety
  and a fast restoration time.
home: https://github.com/uroni/urbackup_backend
host_mounts: []
icon: https://media.sys.truenas.net/apps/urbackup/icons/icon.png
keywords:
- backup
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: urbackup
run_as_context:
- description: Container [urbackup-server] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/uroni/urbackup_backend
- https://hub.docker.com/r/uroni/urbackup-server
title: UrBackup
train: community
version: 1.1.2
