annotations:
  min_scale_version: 24.10.2.2
app_version: v2.9.0
capabilities:
- description: Netdata is able to change file ownership arbitrarily
  name: CHOWN
- description: Netdata is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Netdata is able to bypass permission checks for file operations
  name: FOWNER
- description: Netdata is able to change group ID of processes
  name: SETGID
- description: Netdata is able to change user ID of processes
  name: SETUID
- description: Netdata is able to trace and control other processes
  name: SYS_PTRACE
- description: Netdata is able to perform raw I/O operations
  name: SYS_RAWIO
categories:
- monitoring
changelog_url: https://learn.netdata.cloud/
date_added: '2024-08-02'
description: Real-time performance monitoring, done right!
home: https://www.netdata.cloud/
host_mounts:
- description: Required to read the OS release information.
  host_path: /etc/os-release
- description: Required to read the user information.
  host_path: /etc/passwd
- description: Required to read the group information.
  host_path: /etc/group
- description: Required to read the hostname information.
  host_path: /etc/hostname
- description: Required to read the processes information.
  host_path: /proc
- description: Required to read the system information.
  host_path: /sys
- description: Required to read the docker information.
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/netdata/icons/icon.png
keywords:
- alerting
- metric
- monitoring
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: netdata
run_as_context:
- description: Container [netdata] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/netdata/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/netdata/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/netdata/screenshots/screenshot3.png
sources:
- https://www.netdata.cloud/
- https://github.com/netdata/helmchart
- https://hub.docker.com/r/netdata/netdata
- https://github.com/netdata/netdata
title: Netdata
train: stable
version: 1.4.2
