app_version: 0.6.0
capabilities:
- description: Omni Tools is able to change file ownership arbitrarily
  name: CHOWN
- description: Omni Tools is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Omni Tools is able to bypass permission checks for file operations
  name: FOWNER
- description: Omni Tools is able to change group ID of processes
  name: SETGID
- description: Omni Tools is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/iib0011/omni-tools/releases
date_added: '2025-07-11'
description: Self-hosted collection of powerful web-based tools for everyday tasks.
  No ads, no tracking, just fast, accessible utilities right from your browser!
home: https://omnitools.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/omni-tools/icons/icon.svg
keywords:
- utilities
- tools
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: omni-tools
run_as_context:
- description: Container [omni-tools] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/iib0011/omni-tools
- https://hub.docker.com/r/iib0011/omni-tools
title: Omni Tools
train: community
version: 1.1.2
