app_version: 25.09.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/chrislongros/anki-sync-server-enhanced/releases
date_added: '2026-02-09'
description: Self-hosted Anki sync server with multi-user support, automated backups,
  and monitoring. Built from official Anki source.
home: https://github.com/chrislongros/anki-sync-server-enhanced
host_mounts: []
icon: https://media.sys.truenas.net/apps/anki-sync-server/icons/icon.png
keywords:
- anki
- sync
- flashcards
- spaced-repetition
- education
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: anki-sync-server
run_as_context:
- description: Container [anki] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/chrislongros/anki-sync-server-enhanced
- https://github.com/ankitects/anki
title: Anki Sync Server
train: community
version: 1.1.1
