app_version: 26.5.4
capabilities: []
categories:
- security
changelog_url: https://github.com/keycloak/keycloak/releases
date_added: '2025-08-08'
description: Open Source Identity and Access Management For Modern Applications and
  Services
home: https://www.keycloak.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/keycloak/icons/icon.svg
keywords:
- authentication
- authorization
- sso
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: keycloak
run_as_context:
- description: Container [keycloak] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/keycloak/keycloak
- https://www.keycloak.org/server/all-config#category-database
title: Keycloak
train: community
version: 1.2.1
