app_version: 1.31.13
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/msgbyte/tianji/blob/master/CHANGELOG.md
date_added: '2025-01-09'
description: Tianji - Insight into everything, Website Analytics + Uptime Monitor
  + Server Status. not only another GA alternatives
home: https://tianji.msgbyte.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/tianji/icons/icon.svg
keywords:
- analytics
- monitoring
- uptime
- status
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tianji
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [tianji] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/tianji/screenshots/screenshot6.png
sources:
- https://github.com/msgbyte/tianji
title: Tianji
train: community
version: 1.2.2
