app_version: v2025.12.0
capabilities: []
categories:
- media
changelog_url: https://github.com/wizarrrr/wizarr/releases
date_added: '2025-07-11'
description: Wizarr is an advanced user invitation and management system for Jellyfin,
  Plex, Emby etc.
home: https://github.com/wizarrrr/wizarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/wizarr/icons/icon.png
keywords:
- media
- invitation
- management
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: wizarr
run_as_context:
- description: Container [wizarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/wizarrrr/wizarr
title: Wizarr
train: community
version: 1.1.1
