app_version: 3.6.0.0
capabilities:
- description: Radicale is able to change file ownership arbitrarily
  name: CHOWN
- description: Radicale is able to send signals to any process
  name: KILL
- description: Radicale is able to change group ID of processes
  name: SETGID
- description: Radicale is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/tomsquest/docker-radicale/releases
date_added: '2025-10-22'
description: Free and Open-Source CalDAV and CardDAV Server
home: https://github.com/tomsquest/docker-radicale
host_mounts: []
icon: https://media.sys.truenas.net/apps/radicale/icons/icon.svg
keywords:
- calendar
- contacts
- caldav
- carddav
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: radicale
run_as_context:
- description: Container [radicale] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/tomsquest/docker-radicale
- https://github.com/tomsquest/docker-radicale
title: Radicale
train: community
version: 1.1.1
