annotations:
  min_scale_version: 24.10.2.2
app_version: 2.32.1
capabilities: []
categories:
- media
changelog_url: https://github.com/advplyr/audiobookshelf/releases
date_added: '2024-08-02'
description: Audiobookshelf is a self-hosted audiobook and podcast server
home: https://www.audiobookshelf.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/audiobookshelf/icons/icon.svg
keywords:
- media
- audiobook
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: audiobookshelf
run_as_context:
- description: Container [audiobookshelf] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [opds] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/audiobookshelf/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/audiobookshelf/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/audiobookshelf/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/audiobookshelf/screenshots/screenshot4.jpg
sources:
- https://ghcr.io/advplyr/audiobookshelf
- https://github.com/advplyr/audiobookshelf
title: Audiobookshelf
train: community
version: 1.5.1
