app_version: 2.7.9
capabilities: []
categories:
- media
changelog_url: https://github.com/music-assistant/server/releases
date_added: '2025-10-13'
description: Music Assistant is a music library manager for your offline and online
  music sources which can easily stream your favourite music to a wide range of supported
  players and be combined with the power of Home Assistant!
home: https://www.music-assistant.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/music-assistant/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: music-assistant
run_as_context:
- description: Container [music-assistant] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://music-assistant.io
- https://github.com/music-assistant/server
title: Music Assistant
train: community
version: 1.1.4
