app_version: v1.1.4
capabilities:
- description: Profilarr is able to change file ownership arbitrarily
  name: CHOWN
- description: Profilarr is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Profilarr is able to bypass permission checks for file operations
  name: FOWNER
- description: Profilarr is able to change group ID of processes
  name: SETGID
- description: Profilarr is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/Dictionarry-Hub/profilarr/releases
date_added: '2025-07-08'
description: Profilarr is a Configuration Management Platform for Radarr/Sonarr
home: https://dictionarry.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/profilarr/icons/icon.svg
keywords:
- media
- management
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: profilarr
run_as_context:
- description: Container [profilarr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/Dictionarry-Hub/profilarr
- https://hub.docker.com/r/santiagosayshey/profilarr
title: Profilarr
train: community
version: 1.1.1
