app_version: 2.9.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/gotify/server/releases
date_added: '2025-06-30'
description: A simple server for sending and receiving messages in real-time per WebSocket.
  (Includes a sleek web-ui)
home: https://gotify.net
host_mounts: []
icon: https://media.sys.truenas.net/apps/gotify/icons/icon.png
keywords:
- notifications
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gotify
run_as_context:
- description: Container [gotify] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/gotify/server
title: Gotify
train: community
version: 1.1.1
