app_version: v4.13
capabilities: []
categories:
- financial
changelog_url: https://github.com/SChernykh/p2pool/releases
date_added: '2026-02-05'
description: Run your own node of P2Pool, a decentralized Monero mining pool.
home: https://p2pool.io
host_mounts:
- description: Hugepages device
  host_path: /dev/hugepages
icon: https://media.sys.truenas.net/apps/p2pool/icons/icon.png
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
- mining
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: p2pool
run_as_context:
- description: Container [p2pool] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://p2pool.io
- https://github.com/SChernykh/p2pool
- https://github.com/sethforprivacy/p2pool-docker
title: P2Pool
train: community
version: 1.1.1
