app_version: 0.24.4
capabilities: []
categories:
- media
changelog_url: https://github.com/slskd/slskd/releases
date_added: '2026-01-29'
description: A modern client-server application for the Soulseek file-sharing network.
home: https://github.com/slskd/slskd
host_mounts: []
icon: https://media.sys.truenas.net/apps/slskd/icons/icon.svg
keywords:
- soulseek
- file-sharing
- p2p
- music
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: slskd
run_as_context:
- description: Container [slskd] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/slskd/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/slskd/screenshots/screenshot2.png
sources:
- https://github.com/slskd/slskd
title: slskd
train: community
version: 1.1.3
