app_version: stable
capabilities: []
categories:
- media
date_added: '2025-05-06'
description: NextPVR is a personal video recorder application, with the goal making
  it easy to watch or record live TV
home: http://nextpvr.com/
host_mounts:
- description: Digital Video Broadcast (DVB) device
  host_path: /dev/dvb
icon: https://media.sys.truenas.net/apps/nextpvr/icons/icon.webp
keywords:
- nextpvr
- livetv
- streaming
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: nextpvr
run_as_context:
- description: Container [nextpvr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/r/nextpvr/nextpvr_amd64
title: NextPVR
train: community
version: 1.1.1
