app_version: 9.2.4
capabilities: []
categories:
- media
changelog_url: https://github.com/plexguide/Huntarr.io/releases
date_added: '2025-09-24'
description: A specialized utility that automates discovering missing and upgrading
  your media collection!
home: https://github.com/plexguide/Huntarr.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/huntarr/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: huntarr
run_as_context:
- description: Container [huntarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/plexguide/Huntarr.io
title: Huntarr
train: community
version: 1.1.2
