app_version: '0.15'
capabilities: []
categories:
- productivity
changelog_url: https://github.com/brufdev/many-notes/releases
date_added: '2025-07-31'
description: Many Notes is a Markdown note-taking web application designed for simplicity!
  Easily create or import your vaults and organize your thoughts right away.
home: https://github.com/brufdev/many-notes
host_mounts: []
icon: https://media.sys.truenas.net/apps/many-notes/icons/icon.svg
keywords:
- documentation
- knowledgebase
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: many-notes
run_as_context:
- description: Container [many-notes] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
screenshots: []
sources:
- https://github.com/brufdev/many-notes
title: Many Notes
train: community
version: 1.1.1
