annotations:
  min_scale_version: 24.10.2.2
app_version: 1.2.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/Freika/dawarich/releases
date_added: '2025-05-14'
description: Dawarich is a self-hostable alternative to Google Location History (Google
  Maps Timeline)
home: https://dawarich.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/dawarich/icons/icon.svg
keywords:
- location
- history
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dawarich
run_as_context:
- description: Container [app] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgis] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [sidekiq] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/dawarich/screenshots/screenshot1.jpg
- https://media.sys.truenas.net/apps/dawarich/screenshots/screenshot2.jpg
- https://media.sys.truenas.net/apps/dawarich/screenshots/screenshot3.jpg
sources:
- https://github.com/Freika/dawarich
title: Dawarich
train: community
version: 1.4.1
