app_version: 11.4.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/mattermost/mattermost/releases
date_added: '2025-09-04'
description: Mattermost is an open source platform for secure collaboration across
  the entire software development lifecycle..
home: https://mattermost.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mattermost/icons/icon.svg
keywords:
- collaboration
- communication
- team
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mattermost
run_as_context:
- description: Container [mattermost] runs as non-root user and group.
  gid: 2000
  group_name: Host group is [unknown (2000)]
  uid: 2000
  user_name: Host user is [unknown (2000)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/mattermost/docker
- https://hub.docker.com/r/mattermost/mattermost-team-edition
- https://docs.mattermost.com/administration-guide/configure/environment-configuration-settings.html
title: Mattermost
train: community
version: 1.1.3
