app_version: 4.5.0
capabilities:
- description: Grocy is able to change file ownership arbitrarily
  name: CHOWN
- description: Grocy is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Grocy is able to bypass permission checks for file operations
  name: FOWNER
- description: Grocy is able to change group ID of processes
  name: SETGID
- description: Grocy is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/grocy/grocy/releases
date_added: '2025-07-07'
description: Grocy is a web-based self-hosted groceries & household management solution
  for your home
home: https://grocy.info/
host_mounts: []
icon: https://media.sys.truenas.net/apps/grocy/icons/icon.svg
keywords:
- groceries
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: grocy
run_as_context:
- description: Container [grocy] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/linuxserver/docker-grocy
- https://github.com/grocy/grocy
- https://grocy.info/
title: Grocy
train: community
version: 1.1.0
