app_version: v2.0.6
capabilities: []
categories:
- networking
changelog_url: https://github.com/openspeedtest/Docker-Image/tags
date_added: '2025-02-05'
description: "SpeedTest by OpenSpeedTest\u2122 is a Free and Open-Source HTML5 Network\
  \ Performance Estimation Tool"
home: https://openspeedtest.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/open-speed-test/icons/icon.svg
keywords:
- speedtest
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: open-speed-test
run_as_context:
- description: Container [open-speed-test] runs as non-root user and group.
  gid: 101
  group_name: Host group is [systemd-timesync]
  uid: 101
  user_name: Host user is [systemd-timesync]
screenshots:
- https://media.sys.truenas.net/apps/open-speed-test/screenshots/screenshot1.gif
sources:
- https://github.com/openspeedtest/Speed-Test
title: Open Speed Test
train: community
version: 1.1.2
