app_version: v0.1.74
capabilities: []
categories:
- productivity
changelog_url: https://github.com/donetick/donetick/releases
date_added: '2026-02-11'
description: Donetick is a self-hosted to-do list and habit tracker.
home: https://github.com/donetick/donetick
host_mounts: []
icon: https://media.sys.truenas.net/apps/donetick/icons/icon.svg
keywords:
- tasks
- checklist
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: donetick
run_as_context:
- description: Container [donetick] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/donetick/donetick
- https://hub.docker.com/r/donetick/donetick
title: Donetick
train: community
version: 1.1.0
