app_version: 1.1.2-stable
capabilities: []
categories:
- storage
changelog_url: https://github.com/gtsteffaniak/filebrowser/releases
date_added: '2026-01-23'
description: The best free self-hosted web-based file manager.
home: https://filebrowserquantum.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/filebrowser-quantum/icons/icon.svg
keywords:
- files
- browser
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: filebrowser-quantum
run_as_context:
- description: Container [filebrowser-quantum] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/filebrowser-quantum/screenshots/screenshot6.png
sources:
- https://github.com/gtsteffaniak/filebrowser
title: FileBrowser Quantum
train: community
version: 1.1.2
