app_version: d3be371a-ls259
capabilities:
- description: LazyLibrarian is able to change file ownership arbitrarily
  name: CHOWN
- description: LazyLibrarian is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: LazyLibrarian is able to bypass permission checks for file operations
  name: FOWNER
- description: LazyLibrarian is able to change group ID of processes
  name: SETGID
- description: LazyLibrarian is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/linuxserver/docker-lazylibrarian/releases
date_added: '2025-04-22'
description: LazyLibrarian is a program to follow authors and grab metadata for all
  your digital reading needs.
home: https://gitlab.com/LazyLibrarian/LazyLibrarian
host_mounts: []
icon: https://media.sys.truenas.net/apps/lazylibrarian/icons/icon.webp
keywords:
- media
- ebooks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: lazylibrarian
run_as_context:
- description: Container [lazylibrarian] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
sources:
- https://github.com/linuxserver/docker-lazylibrarian
- https://gitlab.com/LazyLibrarian/LazyLibrarian
title: LazyLibrarian
train: community
version: 1.1.5
