app_version: 2.10.3
capabilities:
- description: Wyze Bridge is able to change file ownership arbitrarily
  name: CHOWN
- description: Wyze Bridge is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Wyze Bridge is able to bypass permission checks for file operations
  name: FOWNER
- description: Wyze Bridge is able to send signals to any process
  name: KILL
- description: Wyze Bridge is able to change group ID of processes
  name: SETGID
- description: Wyze Bridge is able to change user ID of processes
  name: SETUID
categories:
- security
changelog_url: https://github.com/mrlt8/docker-wyze-bridge/releases
date_added: '2025-01-31'
description: Create a local WebRTC, RTSP, RTMP, or HLS/Low-Latency HLS stream for
  most of your Wyze cameras
home: https://github.com/mrlt8/docker-wyze-bridge
host_mounts: []
icon: https://media.sys.truenas.net/apps/wyze-bridge/icons/icon.png
keywords:
- camera
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: wyze-bridge
run_as_context:
- description: Container [wyze-bridge] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/wyze-bridge/screenshots/screenshot1.png
sources:
- https://github.com/mrlt8/docker-wyze-bridge
title: Wyze Bridge
train: community
version: 1.1.1
