app_version: 2.4.0
capabilities: []
categories:
- media
changelog_url: https://github.com/photoview/photoview/releases
date_added: '2025-07-15'
description: Photo gallery for self-hosted personal servers
home: https://photoview.github.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/photoview/icons/icon.svg
keywords:
- media
- photos
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: photoview
run_as_context:
- description: Container [photoview] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/photoview/photoview
- https://hub.docker.com/r/photoview/photoview
title: Photoview
train: community
version: 1.1.0
