app_version: 1.11.0
capabilities:
- description: Anything LLM is able to perform system administration operations
  name: SYS_ADMIN
categories:
- ai
changelog_url: https://github.com/Mintplex-Labs/anything-llm/releases
date_added: '2025-08-11'
description: Anything-LLM is the all-in-one Desktop & Docker AI application with built-in
  RAG, AI agents, No-code agent builder, MCP compatibility, and more.
home: https://anythingllm.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/anything-llm/icons/icon.svg
keywords:
- ai
- llm
- webui
- anything-llm
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: anything-llm
run_as_context:
- description: Container [anything-llm] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/Mintplex-Labs/anything-llm
title: Anything LLM
train: community
version: 1.1.2
