app_version: 3.15.4
capabilities: []
categories:
- productivity
changelog_url: https://help.iconik.backlight.co/hc/en-us/articles/25304675738135-ISG-And-Edge-Transcoder-Release-Notes
date_added: '2024-11-19'
description: The iconik Storage Gateway (ISG) allows you to use your on-premise storage
  with iconik in the cloud.
home: https://iconik.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/iconik-storage-gateway/icons/icon.svg
keywords:
- iconik
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: iconik-storage-gateway
run_as_context:
- description: Container [iconik] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/truenas/iconik-storage-gateway-docker
- https://app.iconik.io/help/pages/isg
title: Iconik Storage Gateway
train: community
version: 1.1.2
