app_version: v1.9.10
capabilities:
- description: Satisfactory is able to change file ownership arbitrarily
  name: CHOWN
- description: Satisfactory is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Satisfactory is able to bypass permission checks for file operations
  name: FOWNER
- description: Satisfactory is able to change group ID of processes
  name: SETGID
- description: Satisfactory is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://github.com/wolveix/satisfactory-server/releases
date_added: '2025-01-03'
description: A Dockerized version of the Satisfactory dedicated server
home: https://github.com/wolveix/satisfactory-server
host_mounts: []
icon: https://media.sys.truenas.net/apps/satisfactory-server/icons/icon.png
keywords:
- games
- server
- satisfactory
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: satisfactory-server
run_as_context:
- description: Container [satisfactory] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/wolveix/satisfactory-server
title: Satisfactory Server
train: community
version: 1.1.1
