app_version: 0.8.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/RackulaLives/Rackula/releases
date_added: '2026-01-17'
description: Drag and drop rack visualizer
home: https://github.com/RackulaLives/Rackula
host_mounts: []
icon: https://media.sys.truenas.net/apps/rackula/icons/icon.svg
keywords:
- rack
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rackula
run_as_context:
- description: Container [rackula] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [rackula-api] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/RackulaLives/Rackula
title: Rackula
train: community
version: 1.1.1
