annotations:
  min_scale_version: 24.10.2.2
app_version: 2026.2.1-java21
capabilities:
- description: Minecraft is able to change file ownership arbitrarily
  name: CHOWN
- description: Minecraft is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Minecraft is able to bypass permission checks for file operations
  name: FOWNER
- description: Minecraft is able to use raw and packet sockets
  name: NET_RAW
- description: Minecraft is able to change group ID of processes
  name: SETGID
- description: Minecraft is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://github.com/itzg/docker-minecraft-server/releases
date_added: '2024-08-05'
description: Minecraft dedicated server for Java platform hosts a world for multiplayer
  game. Players can join the server using the Java client on Desktops.
home: https://www.minecraft.net/en-us
host_mounts: []
icon: https://media.sys.truenas.net/apps/minecraft/icons/icon.svg
keywords:
- world
- building
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: minecraft
run_as_context:
- description: Container [minecraft] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://www.minecraft.net/en-us
- https://github.com/itzg/docker-minecraft-server
title: Minecraft Server (Java)
train: community
version: 1.14.2
