app_version: 1.9.1
capabilities: []
categories:
- networking
changelog_url: https://github.com/fosrl/newt/releases
date_added: '2025-05-09'
description: Newt is a fully user space WireGuard tunnel client and TCP/UDP proxy,
  designed to securely expose private resources controlled by Pangolin. By using Newt,
  you don't need to manage complex WireGuard tunnels and NATing.
home: https://github.com/fosrl/newt
host_mounts: []
icon: https://media.sys.truenas.net/apps/newt/icons/icon.svg
keywords:
- tunneling
- proxy
- wireguard
- pangolin
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: newt
run_as_context:
- description: Container [newt] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/fosrl/newt
- https://hub.docker.com/r/fosrl/newt
title: Newt
train: community
version: 1.1.1
