app_version: 2026.2.2
capabilities: []
categories:
- games
changelog_url: https://github.com/itzg/docker-minecraft-bedrock-server/releases
date_added: '2025-01-15'
description: 'Minecraft dedicated server for Bedrock platform hosts a world for multiplayer
  game.

  Players can join the server using the Bedrock client on Desktops, Mobiles, and consoles.

  '
home: https://www.minecraft.net/en-us
host_mounts: []
icon: https://media.sys.truenas.net/apps/minecraft-bedrock/icons/icon.svg
keywords:
- world
- building
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: minecraft-bedrock
run_as_context:
- description: Container [minecraft-bedrock] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://www.minecraft.net/en-us
- https://github.com/itzg/docker-minecraft-bedrock-server
title: Minecraft Server (Bedrock)
train: community
version: 1.1.4
