app_version: stable-2.0.72
capabilities:
- description: Factorio is able to change file ownership arbitrarily
  name: CHOWN
- description: Factorio is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Factorio is able to bypass permission checks for file operations
  name: FOWNER
- description: Factorio is able to change group ID of processes
  name: SETGID
- description: Factorio is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://wiki.factorio.com/Version_history
date_added: '2025-07-02'
description: Factorio headless server in a Docker container
home: https://factorio.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/factorio/icons/icon.png
keywords:
- games
- server
- factorio
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: factorio
run_as_context:
- description: Container [factorio] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/factoriotools/factorio-docker
- https://hub.docker.com/r/factoriotools/factorio/
title: Factorio Server
train: community
version: 1.1.1
