app_version: 1.16.0
capabilities: []
categories:
- media
changelog_url: https://github.com/CorentinTh/enclosed/releases
date_added: '2025-07-15'
description: Enclosed is a minimalistic web app designed for sending private and secure
  notes.
home: https://enclosed.cc/
host_mounts: []
icon: https://media.sys.truenas.net/apps/enclosed/icons/icon.svg
keywords:
- media
- series
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: enclosed
run_as_context:
- description: Container [enclosed] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/CorentinTh/enclosed
title: Enclosed
train: community
version: 1.1.2
