app_version: latest
capabilities:
- description: SickGear is able to change file ownership arbitrarily
  name: CHOWN
- description: SickGear is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: SickGear is able to bypass permission checks for file operations
  name: FOWNER
- description: SickGear is able to change group ID of processes
  name: SETGID
- description: SickGear is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/SickGear/SickGear/releases
date_added: '2025-06-18'
description: SickGear has proven the most reliable stable TV fork of the great Sick-Beard
  to fully automate TV enjoyment with innovation.
home: https://github.com/SickGear/SickGear
host_mounts: []
icon: https://media.sys.truenas.net/apps/sickgear/icons/icon.png
keywords:
- sickgear
- sickbeard
- tv
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: sickgear
run_as_context:
- description: Container [sickgear] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/SickGear/SickGear
title: SickGear
train: community
version: 1.1.1
