annotations:
  min_scale_version: 24.10.2.2
app_version: 1.0.0
capabilities:
- description: Tftpd is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Tftpd is able to change group ID of processes
  name: SETGID
- description: Tftpd is able to change user ID of processes
  name: SETUID
- description: Tftpd is able to use chroot() system call
  name: SYS_CHROOT
categories:
- networking
date_added: '2024-08-27'
description: A lightweight tftp-server
home: https://github.com/truenas/containers/tree/main/apps/tftpd-hpa
host_mounts: []
icon: https://media.sys.truenas.net/apps/tftpd-hpa/icons/icon.png
keywords:
- tftp
- netboot
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tftpd-hpa
run_as_context:
- description: Container [tftpd] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/truenas/containers/tree/main/apps/tftpd-hpa
- https://hub.docker.com/r/ixsystems/tftpd-hpa
title: TFTP Server
train: community
version: 1.3.1
