annotations:
  min_scale_version: 24.10.2.2
app_version: 2.38.1
capabilities: []
categories:
- management
changelog_url: https://github.com/portainer/portainer/releases
date_added: '2024-08-07'
description: Container management made easy
home: https://www.portainer.io
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/portainer/icons/icon.png
keywords:
- docker
- compose
- container
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: portainer
run_as_context:
- description: Container [portainer] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/portainer/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/portainer/screenshots/screenshot2.png
sources:
- https://www.portainer.io
- https://github.com/portainer/portainer
title: Portainer
train: community
version: 1.6.2
