app_version: 2.0.8
capabilities: []
categories:
- productivity
changelog_url: https://github.com/TBosak/mkfd/releases
date_added: '2025-11-10'
description: Mkfd is a powerful RSS feed generator supporting web scraping, API data
  sources, and IMAP email feeds with webhook integration.
home: https://github.com/TBosak/mkfd
host_mounts: []
icon: https://media.sys.truenas.net/apps/mkfd/icons/icon.svg
keywords:
- rss
- feed-generator
- web-scraping
- email
- imap
- webhook
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mkfd
run_as_context:
- description: Container [mkfd] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/TBosak/mkfd
title: Mkfd
train: community
version: 1.1.0
