app_version: 1.13.10
capabilities:
- description: Speedtest Tracker is able to change file ownership arbitrarily
  name: CHOWN
- description: Speedtest Tracker is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Speedtest Tracker is able to bypass permission checks for file operations
  name: FOWNER
- description: Speedtest Tracker is able to change group ID of processes
  name: SETGID
- description: Speedtest Tracker is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/alexjustesen/speedtest-tracker/releases
date_added: '2025-07-01'
description: Speedtest Tracker is a self-hosted application that monitors the performance
  and uptime of your internet connection.
home: https://speedtest-tracker.dev
host_mounts: []
icon: https://media.sys.truenas.net/apps/speedtest-tracker/icons/icon.png
keywords:
- speedtest
- tracker
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: speedtest-tracker
run_as_context:
- description: Container [speedtest-tracker] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/linuxserver/docker-speedtest-tracker
- https://github.com/alexjustesen/speedtest-tracker
title: Speedtest Tracker
train: community
version: 1.1.3
