app_version: '0.3'
capabilities: []
categories:
- financial
changelog_url: https://github.com/vtnerd/monero-lws/tags
date_added: '2025-03-27'
description: Monero LWS is a Monero light-wallet server, currently compatible with
  MyMonero and Edge.
home: https://github.com/vtnerd/monero-lws
host_mounts: []
icon: https://media.sys.truenas.net/apps/monero-lws/icons/icon.png
keywords:
- monero
- cryptocurrency
- wallet
- rpc
- blockchain
- privacy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: monero-lws
run_as_context:
- description: Container [monero-lws] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/vtnerd/monero-lws
title: Monero LWS
train: community
version: 1.2.1
