app_version: v2.13.5
capabilities: []
categories:
- productivity
changelog_url: https://github.com/linkwarden/linkwarden/releases
date_added: '2025-08-13'
description: Linkwarden is a self-hosted, open-source collaborative bookmark manager
  to collect, read, annotate, and fully preserve what matters, all in one place.
home: https://docs.linkwarden.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/linkwarden/icons/icon.png
keywords:
- links
- bookmarks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: linkwarden
run_as_context:
- description: Container [linkwarden] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [meilisearch] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://docs.linkwarden.app/
- https://github.com/linkwarden/linkwarden
title: Linkwarden
train: community
version: 1.2.1
