app_version: 2.2.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/alam00000/bentopdf/releases
date_added: '2025-11-04'
description: A Privacy First PDF Toolkit
home: https://bentopdf.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bentopdf/icons/icon.svg
keywords:
- pdf
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bentopdf
run_as_context:
- description: Container [bentopdf] runs as non-root user and group.
  gid: 101
  group_name: Host group is [systemd-timesync]
  uid: 101
  user_name: Host user is [systemd-timesync]
screenshots: []
sources:
- https://github.com/alam00000/bentopdf
title: BentoPDF
train: community
version: 1.1.0
