annotations:
  min_scale_version: 24.10.2.2
app_version: 1.43.0.10492-121068a07
capabilities:
- description: Plex is able to change file ownership arbitrarily
  name: CHOWN
- description: Plex is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Plex is able to bypass permission checks for file operations
  name: FOWNER
- description: Plex is able to send signals to any process
  name: KILL
- description: Plex is able to change group ID of processes
  name: SETGID
- description: Plex is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://forums.plex.tv/t/plex-media-server/30447/
date_added: '2024-07-23'
description: Plex is a media server that allows you to stream your media to any Plex
  client.
home: https://plex.tv
host_mounts: []
icon: https://media.sys.truenas.net/apps/plex/icons/icon.png
keywords:
- plex
- media
- entertainment
- movies
- series
- tv
- streaming
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: plex
run_as_context:
- description: Container [plex] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/plex/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/plex/screenshots/screenshot2.png
sources:
- https://plex.tv
- https://hub.docker.com/r/plexinc/pms-docker
title: Plex
train: stable
version: 1.3.2
