app_version: v1.94.2
capabilities:
- description: Tailscale is able to change file ownership arbitrarily
  name: CHOWN
- description: Tailscale is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Tailscale is able to bypass permission checks for file operations
  name: FOWNER
- description: Tailscale is able to perform network administration tasks
  name: NET_ADMIN
- description: Tailscale is able to use raw and packet sockets
  name: NET_RAW
- description: Tailscale is able to load and unload kernel modules
  name: SYS_MODULE
categories:
- networking
changelog_url: https://tailscale.com/changelog#client
date_added: '2024-07-30'
description: Secure remote access to shared resources
home: https://tailscale.com/
host_mounts:
- description: Network device
  host_path: /dev/net/tun
icon: https://media.sys.truenas.net/apps/tailscale/icons/icon.png
keywords:
- vpn
- tailscale
- wireguard
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tailscale
run_as_context:
- description: Container [tailscale] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://tailscale.com/
- https://hub.docker.com/r/tailscale/tailscale
title: Tailscale
train: community
version: 1.4.2
