annotations:
  min_scale_version: 24.10.2.2
app_version: 1.6.13-apache
capabilities:
- description: Roundcube is able to change file ownership arbitrarily
  name: CHOWN
- description: Roundcube is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Roundcube is able to bypass permission checks for file operations
  name: FOWNER
- description: Roundcube is able to change group ID of processes
  name: SETGID
- description: Roundcube is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/roundcube/roundcubemail/releases
date_added: '2024-09-11'
description: Roundcube is a browser-based multilingual IMAP client with an application-like
  user interface.
home: https://roundcube.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/roundcube/icons/icon.png
keywords:
- webmail
- email
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: roundcube
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [roundcube] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/roundcube/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/roundcube/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/roundcube/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/roundcube/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/roundcube/screenshots/screenshot5.png
sources:
- https://roundcube.net/
- https://hub.docker.com/r/roundcube/roundcubemail/
title: Roundcube
train: community
version: 1.5.2
