annotations:
  min_scale_version: 24.10.2.2
app_version: v2.7.0
capabilities: []
categories:
- storage
changelog_url: https://github.com/drakkan/sftpgo/releases
date_added: '2024-09-16'
description: SFTPGo is a fully featured and highly configurable SFTP server with optional
  HTTP/S, FTP/S and WebDAV support - S3, Google Cloud Storage, Azure Blob
home: https://github.com/drakkan/sftpgo
host_mounts: []
icon: https://media.sys.truenas.net/apps/sftpgo/icons/icon.png
keywords:
- sftp
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: sftpgo
run_as_context:
- description: Container [sftpgo] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/r/drakkan/sftpgo
- https://github.com/drakkan/sftpgo
title: SFTPGo
train: community
version: 1.3.2
