annotations:
  min_scale_version: 24.10.2.2
app_version: 2.0.14
capabilities:
- description: Syncthing is able to change file ownership arbitrarily
  name: CHOWN
- description: Syncthing is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Syncthing is able to bypass permission checks for file operations
  name: FOWNER
- description: Syncthing is able to set file capabilities on other files
  name: SETFCAP
- description: Syncthing is able to change group ID of processes
  name: SETGID
- description: Syncthing is able to transfer capabilities between processes
  name: SETPCAP
- description: Syncthing is able to change user ID of processes
  name: SETUID
- description: Syncthing is able to perform system administration operations
  name: SYS_ADMIN
categories:
- storage
changelog_url: https://github.com/syncthing/syncthing/releases
date_added: '2024-07-23'
description: Syncthing is a continuous file synchronization program.
home: https://syncthing.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/syncthing/icons/icon.svg
keywords:
- sync
- file-sharing
- backup
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: syncthing
run_as_context:
- description: Container [syncthing] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/syncthing/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/syncthing/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/syncthing/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/syncthing/screenshots/screenshot4.png
sources:
- https://syncthing.net/
- https://github.com/syncthing/syncthing
- https://hub.docker.com/r/syncthing/syncthing
title: Syncthing
train: stable
version: 1.3.1
