annotations:
  min_scale_version: 24.10.2.2
app_version: 3.0.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/distribution/distribution/releases
date_added: '2024-08-02'
description: Distribution is a toolkit to pack, ship, store, and deliver container
  content
home: https://github.com/distribution/distribution
host_mounts: []
icon: https://media.sys.truenas.net/apps/distribution/icons/icon.svg
keywords:
- registry
- container
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: distribution
run_as_context:
- description: Container [distribution] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/_/registry
- https://distribution.github.io/distribution/
- https://github.com/distribution/distribution
title: Distribution
train: community
version: 1.3.1
