app_version: latest
capabilities:
- description: Excalidraw is able to change file ownership arbitrarily
  name: CHOWN
- description: Excalidraw is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Excalidraw is able to bypass permission checks for file operations
  name: FOWNER
- description: Excalidraw is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Excalidraw is able to change group ID of processes
  name: SETGID
- description: Excalidraw is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/excalidraw/excalidraw/releases
date_added: '2025-09-08'
description: Virtual whiteboard for sketching hand-drawn like diagrams
home: https://excalidraw.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/excalidraw/icons/icon.svg
keywords:
- diagram
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: excalidraw
run_as_context:
- description: Container [excalidraw] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/excalidraw/excalidraw
- https://github.com/excalidraw/excalidraw
title: Excalidraw
train: community
version: 1.1.0
