app_version: 11.8.6
capabilities: []
categories:
- database
changelog_url: https://mariadb.com/kb/en/mariadb-community-server-release-notes/
date_added: '2025-03-05'
description: MariaDB server is a community developed fork of MySQL server.
home: https://mariadb.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mariadb/icons/icon.png
keywords:
- database
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mariadb
run_as_context:
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://hub.docker.com/_/mariadb
title: Mariadb
train: community
version: 1.1.2
