app_version: 14.0.2-rootless
capabilities: []
categories:
- productivity
changelog_url: https://forgejo.org/releases/
date_added: '2025-03-28'
description: Forgejo is a self-hosted lightweight software forge. Easy to install
  and low maintenance, it just does the job.
home: https://forgejo.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/forgejo/icons/icon.svg
keywords:
- git
- forgejo
- source control
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: forgejo
run_as_context:
- description: Container [forgejo] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://forgejo.org/
- https://codeberg.org/forgejo/forgejo
title: Forgejo
train: community
version: 1.1.0
