app_version: 26.2.0
capabilities: []
categories:
- management
date_added: '2025-05-26'
description: "is a free, open-source genealogy system for building your family tree\
  \ \u2013 together. Use it standalone or as a companion to Gramps Desktop, with full\
  \ control over your data and privacy as the top priority."
home: https://www.grampsweb.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/gramps-web/icons/icon.svg
keywords:
- gramps
- genealogy
- familytree
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gramps-web
run_as_context:
- description: Container [celery] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [web] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/gramps-project/gramps-web
title: Gramps Web
train: community
version: 1.3.0
