annotations:
  min_scale_version: 24.10.2.2
app_version: 9.3.0
capabilities: []
categories:
- monitoring
changelog_url: https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html
date_added: '2024-08-01'
description: Elasticsearch is the distributed, RESTful search and analytics engine
  at the heart of the Elastic Stack.
home: https://www.elastic.co
host_mounts: []
icon: https://media.sys.truenas.net/apps/elastic-search/icons/icon.svg
keywords:
- search
- elastic
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: elastic-search
run_as_context:
- description: Container [elastic] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://www.elastic.co/
- https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html#docker-configuration-methods
title: Elastic Search
train: stable
version: 1.4.2
