annotations:
  min_scale_version: 24.10.2.2
app_version: 2.20260207.0
capabilities: []
categories:
- media
changelog_url: https://github.com/iv-org/invidious/blob/master/CHANGELOG.md
date_added: '2024-09-05'
description: Invidious is an alternative front-end to YouTube
home: https://invidious.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/invidious/icons/icon.svg
keywords:
- youtube
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: invidious
run_as_context:
- description: Container [companion] runs as non-root user and group.
  gid: 10001
  group_name: Host group is [unknown (10001)]
  uid: 10001
  user_name: Host user is [unknown (10001)]
- description: Container [invidious] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/invidious/screenshots/screenshot6.png
sources:
- https://invidious.io/
- https://quay.io/repository/invidious
title: Invidious
train: community
version: 1.5.2
