app_version: v0.101.3
capabilities:
- description: Trilium is able to change file ownership arbitrarily
  name: CHOWN
- description: Trilium is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Trilium is able to bypass permission checks for file operations
  name: FOWNER
- description: Trilium is able to change group ID of processes
  name: SETGID
- description: Trilium is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/TriliumNext/Trilium/releases
date_added: '2025-09-10'
description: Trilium Notes is a free and open-source, cross-platform hierarchical
  note taking application with focus on building large personal knowledge bases.
home: https://github.com/TriliumNext/Trilium
host_mounts: []
icon: https://media.sys.truenas.net/apps/trilium-notes/icons/icon.svg
keywords:
- productivity
- notes
- knowledge base
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: trilium-notes
run_as_context:
- description: Container [trilium] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot6.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot7.png
- https://media.sys.truenas.net/apps/trilium-notes/screenshots/screenshot8.png
sources:
- https://github.com/TriliumNext/Trilium
title: Trilium Notes
train: community
version: 1.1.2
