app_version: v0.10.0
capabilities: []
categories:
- media
changelog_url: https://github.com/bitmagnet-io/bitmagnet/releases
date_added: '2025-05-27'
description: Bitmagnet is a self-hosted BitTorrent indexer, DHT crawler, content classifier
  and torrent search engine with web UI, GraphQL API and Servarr stack integration.
home: https://bitmagnet.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitmagnet/icons/icon.svg
keywords:
- torrent
- bittorrent
- indexer
- dht
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bitmagnet
run_as_context:
- description: Container [bitmagnet] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/bitmagnet/screenshots/screenshot1.png
sources:
- https://github.com/bitmagnet-io/bitmagnet
title: Bitmagnet
train: community
version: 1.2.0
