annotations:
  min_scale_version: 24.10.2.2
app_version: latest
capabilities: []
categories:
- storage
changelog_url: https://forum.storj.io/tag/official-changelog
date_added: '2024-09-02'
description: Share your storage on the internet and earn.
home: https://www.storj.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/storj/icons/icon.svg
keywords:
- storage
- networking
- financial
- file-sharing
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: storj
run_as_context:
- description: Container [storj] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/storj/screenshots/screenshot1.jpeg
sources:
- https://www.storj.io
title: Storj
train: stable
version: 1.4.2
