app_version: 1.3.4
capabilities:
- description: portracker is able to use raw and packet sockets
  name: NET_RAW
- description: portracker is able to trace and control other processes
  name: SYS_PTRACE
categories:
- monitoring
changelog_url: https://github.com/mostafa-wahied/portracker/releases
date_added: '2025-07-29'
description: A self-hosted, real-time port monitoring and discovery tool.
home: https://github.com/mostafa-wahied/portracker
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/portracker/icons/icon.svg
keywords:
- portracker
- ports
- monitoring
- discovery
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: portracker
run_as_context:
- description: Container [portracker] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/portracker/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/portracker/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/portracker/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/portracker/screenshots/screenshot4.png
sources:
- https://github.com/mostafa-wahied/portracker
- https://hub.docker.com/r/mostafawahied/portracker
title: portracker
train: community
version: 1.1.2
