annotations:
  min_scale_version: 24.10.2.2
app_version: v1.73.0
capabilities: []
categories:
- media
changelog_url: https://github.com/autobrr/autobrr/releases
date_added: '2024-08-01'
description: Autobrr is the modern download automation tool for torrents and usenet.
home: https://github.com/autobrr/autobrr
host_mounts: []
icon: https://media.sys.truenas.net/apps/autobrr/icons/icon.png
keywords:
- media
- torrent
- usenet
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: autobrr
run_as_context:
- description: Container [autobrr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://autobrr.com/installation/docker
- https://github.com/autobrr/autobrr
title: Autobrr
train: community
version: 1.4.0
