annotations:
  min_scale_version: 24.10.2.2
app_version: palworld
capabilities:
- description: Palworld is able to change file ownership arbitrarily
  name: CHOWN
- description: Palworld is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Palworld is able to bypass permission checks for file operations
  name: FOWNER
- description: Palworld is able to send signals to any process
  name: KILL
- description: Palworld is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Palworld is able to change group ID of processes
  name: SETGID
- description: Palworld is able to change user ID of processes
  name: SETUID
- description: Palworld is able to override resource limits
  name: SYS_RESOURCE
categories:
- games
changelog_url: https://github.com/ich777/docker-steamcmd-server/tags
date_added: '2024-08-02'
description: Palworld is a multiplayer, open-world survival crafting game where you
  befriend and collect mysterious creatures called "Pals".
home: https://www.pocketpair.jp/palworld
host_mounts: []
icon: https://media.sys.truenas.net/apps/palworld/icons/icon.webp
keywords:
- game
- palworld
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: palworld
run_as_context:
- description: Container [palworld] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://www.pocketpair.jp/palworld
- https://github.com/ich777/docker-steamcmd-server/tree/palworld
title: Palworld
train: community
version: 1.3.2
