app_version: v1.7.2
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/dockpeek/dockpeek/releases
date_added: '2025-10-24'
description: "Easily access your Docker container web interfaces and keep them up\
  \ to date \u2014 across all your hosts."
home: https://github.com/dockpeek/dockpeek
host_mounts: []
icon: https://media.sys.truenas.net/apps/dockpeek/icons/icon.svg
keywords:
- docker
- ports
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dockpeek
run_as_context:
- description: Container [dockpeek] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/dockpeek/dockpeek
title: Dockpeek
train: community
version: 1.1.0
