app_version: v0.18.4.5
capabilities: []
categories:
- financial
changelog_url: https://www.getmonero.org/blog/tags/releases.html
date_added: '2025-02-21'
description: Monero is a private, decentralized cryptocurrency that keeps your finances
  confidential and secure.
home: https://www.getmonero.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/monerod/icons/icon.png
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: monerod
run_as_context:
- description: Container [monerod] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://www.getmonero.org
- https://github.com/sethforprivacy/simple-monerod-docker
title: Monero Node
train: community
version: 1.2.2
