annotations:
  min_scale_version: 24.10.2.2
app_version: latest
capabilities:
- description: MineOS is able to change file ownership arbitrarily
  name: CHOWN
- description: MineOS is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: MineOS is able to bypass permission checks for file operations
  name: FOWNER
- description: MineOS is able to change group ID of processes
  name: SETGID
- description: MineOS is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://github.com/hexparrot/mineos-node/releases
date_added: '2024-08-02'
description: MineOS is a server front-end to ease managing Minecraft administrative
  tasks.
home: https://github.com/hexparrot/mineos-node
host_mounts: []
icon: https://media.sys.truenas.net/apps/mineos/icons/icon.png
keywords:
- minecraft
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mineos
run_as_context:
- description: Container [mineos] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/mineos/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/hexparrot/mineos/
- https://github.com/hexparrot/mineos-node
title: MineOS
train: community
version: 1.3.2
