annotations:
  min_scale_version: 24.10.2.2
app_version: tshock-1.4.4.9-5.2.4
capabilities: []
categories:
- games
changelog_url: https://github.com/ryansheehan/terraria/releases
date_added: '2024-09-17'
description: Terraria is a land of adventure! A land of mystery! A land that's yours
  to shape, defend, and enjoy.
home: https://terraria.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/terraria/icons/icon.png
keywords:
- adventure
- building
- game
- terraria
- world
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: terraria
run_as_context:
- description: Container [terraria] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://terraria.org/
- https://github.com/ryansheehan/terraria
title: Terraria
train: community
version: 1.3.0
