app_version: 2.2.17
capabilities: []
categories:
- productivity
changelog_url: https://miniflux.app/releases
date_added: '2025-10-30'
description: Miniflux is a minimalist and opinionated feed reader.
home: https://miniflux.app
host_mounts: []
icon: https://media.sys.truenas.net/apps/miniflux/icons/icon.svg
keywords:
- rss
- news
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: miniflux
run_as_context:
- description: Container [miniflux] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://miniflux.app/
- https://github.com/miniflux/v2
title: Miniflux
train: community
version: 1.1.2
