app_version: 0.26.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/toeverything/AFFiNE/releases
date_added: '2025-05-21'
description: AFFiNE is a next-gen knowledge base that brings planning, sorting and
  creating all together. Privacy first, open-source, customizable and ready to use.
home: https://affine.pro
host_mounts: []
icon: https://media.sys.truenas.net/apps/affine/icons/icon.svg
keywords:
- planning
- knowledge base
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: affine
run_as_context:
- description: Container [affine] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/toeverything/AFFiNE
title: AFFiNE
train: community
version: 1.2.1
