app_version: v0.5.9
capabilities:
- description: Tube Archivist is able to change file ownership arbitrarily
  name: CHOWN
- description: Tube Archivist is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Tube Archivist is able to bypass permission checks for file operations
  name: FOWNER
categories:
- media
changelog_url: https://github.com/tubearchivist/tubearchivist/releases
date_added: '2025-08-22'
description: Your self hosted YouTube media server
home: https://tubearchivist.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/tubearchivist/icons/icon.png
keywords:
- media-server
- youtube
- download
- videos
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tubearchivist
run_as_context:
- description: Container [elastic-search] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [tubearchivist] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/tubearchivist/tubearchivist
- https://hub.docker.com/r/bbilly1/tubearchivist
title: Tube Archivist
train: community
version: 1.1.1
