app_version: 0.3.1
capabilities:
- description: Unmanic is able to change file ownership arbitrarily
  name: CHOWN
- description: Unmanic is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Unmanic is able to bypass permission checks for file operations
  name: FOWNER
- description: Unmanic is able to change group ID of processes
  name: SETGID
- description: Unmanic is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/Unmanic/unmanic/releases
date_added: '2025-02-24'
description: Unmanic is a library optimizer
home: https://github.com/Unmanic/unmanic
host_mounts: []
icon: https://media.sys.truenas.net/apps/unmanic/icons/icon.png
keywords:
- optimize
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: unmanic
run_as_context:
- description: Container [unmanic] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/unmanic/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/unmanic/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/unmanic/screenshots/screenshot3.png
sources:
- https://github.com/Unmanic/unmanic
title: Unmanic
train: community
version: 1.1.1
