app_version: v1.2.0
capabilities: []
categories:
- storage
changelog_url: https://github.com/versity/versitygw/releases
date_added: '2025-05-08'
description: The Versity Gateway serves as a bridge between file based, POSIX, storage
  systems and applications that rely on S3 object interfaces. It enables applications
  to interact with file storage using familiar S3 operations like put and get, allowing
  for easy integration and compatibility.
home: https://github.com/versity/versitygw
host_mounts: []
icon: https://media.sys.truenas.net/apps/versitygw/icons/icon.svg
keywords:
- storage
- object-storage
- S3
- versity
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: versitygw
run_as_context:
- description: Container [versity] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/versity/versitygw
title: Versity Gateway
train: community
version: 1.1.2
