annotations:
  min_scale_version: 24.10.2.2
app_version: 16.3.0
capabilities:
- description: Piwigo is able to change file ownership arbitrarily
  name: CHOWN
- description: Piwigo is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Piwigo is able to bypass permission checks for file operations
  name: FOWNER
- description: Piwigo is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Piwigo is able to change group ID of processes
  name: SETGID
- description: Piwigo is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://piwigo.org/forum/viewforum.php?id=23
date_added: '2024-09-19'
description: Piwigo is a photo gallery software for the web that comes with powerful
  features to publish and manage your collection of pictures.
home: https://piwigo.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/piwigo/icons/icon.svg
keywords:
- photo
- gallery
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: piwigo
run_as_context:
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [piwigo] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/piwigo/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/piwigo/screenshots/screenshot2.png
sources:
- https://github.com/linuxserver/docker-piwigo
title: Piwigo
train: community
version: 1.4.1
