app_version: v4.1.0
capabilities: []
categories:
- security
changelog_url: https://github.com/steveiliop56/tinyauth/releases
date_added: '2025-12-15'
description: The simplest way to protect your apps with a login screen.
home: https://tinyauth.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/tinyauth/icons/icon.svg
keywords:
- security
- auth
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tinyauth
run_as_context:
- description: Container [tinyauth] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/steveiliop56/tinyauth
title: TinyAuth
train: community
version: 1.1.1
