app_version: v0.9.0
capabilities:
- description: Omnom is able to change file ownership arbitrarily
  name: CHOWN
- description: Omnom is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Omnom is able to bypass permission checks for file operations
  name: FOWNER
- description: Omnom is able to change group ID of processes
  name: SETGID
- description: Omnom is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/asciimoo/omnom/releases
date_added: '2026-01-20'
description: A web content preservation service
home: https://omnom.zone/
host_mounts: []
icon: https://media.sys.truenas.net/apps/omnom/icons/icon.svg
keywords:
- web
- content
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: omnom
run_as_context:
- description: Container [omnom] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/asciimoo/omnom
title: Omnom
train: community
version: 1.1.0
