annotations:
  min_scale_version: 24.10.2.2
app_version: '251130'
capabilities:
- description: Photoprism is able to change file ownership arbitrarily
  name: CHOWN
- description: Photoprism is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Photoprism is able to bypass permission checks for file operations
  name: FOWNER
- description: Photoprism is able to send signals to any process
  name: KILL
- description: Photoprism is able to change group ID of processes
  name: SETGID
- description: Photoprism is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/photoprism/photoprism/releases
date_added: '2024-08-02'
description: AI-powered app for browsing, organizing & sharing your photo collection.
home: https://photoprism.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/photoprism/icons/icon.svg
keywords:
- media
- photos
- image
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: photoprism
run_as_context:
- description: Container [photoprism] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/photoprism/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/photoprism/screenshots/screenshot2.png
sources:
- https://photoprism.app/
title: Photoprism
train: stable
version: 1.4.2
