annotations:
  min_scale_version: 24.10.2.2
app_version: 10.11.6
capabilities: []
categories:
- media
changelog_url: https://github.com/jellyfin/jellyfin/releases
date_added: '2024-07-30'
description: Jellyfin is a Free Software Media System that puts you in control of
  managing and streaming your media.
home: https://jellyfin.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/jellyfin/icons/icon.svg
keywords:
- entertainment
- movies
- series
- tv
- media
- streaming
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jellyfin
run_as_context:
- description: Container [jellyfin] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/jellyfin/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/jellyfin/screenshots/screenshot2.png
sources:
- https://hub.docker.com/r/jellyfin/jellyfin
- https://jellyfin.org/
title: Jellyfin
train: community
version: 1.3.2
