app_version: 6.12.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/traccar/traccar/releases
date_added: '2025-06-20'
description: Traccar GPS Tracking System
home: https://www.traccar.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/traccar/icons/icon.svg
keywords:
- gps
- tracking
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: traccar
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [traccar] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/traccar/traccar
title: Traccar
train: community
version: 1.2.4
