app_version: 2.58.02
capabilities:
- description: Tdarr Node is able to change file ownership arbitrarily
  name: CHOWN
- description: Tdarr Node is able to bypass permission checks for file operations
  name: FOWNER
- description: Tdarr Node is able to change group ID of processes
  name: SETGID
- description: Tdarr Node is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://home.tdarr.io/download
date_added: '2025-09-10'
description: Tdarr Node is a Distributed Transcoding System
home: https://home.tdarr.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/tdarr-node/icons/icon.png
keywords:
- encode
- transcode
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tdarr-node
run_as_context:
- description: Container [tdarr-node] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://home.tdarr.io/
- https://docs.tdarr.io/docs
title: Tdarr Node
train: community
version: 1.1.2
