annotations:
  min_scale_version: 24.10.2.2
app_version: 4.0.16.2946
capabilities: []
categories:
- media
changelog_url: https://github.com/Sonarr/Sonarr/releases
date_added: '2024-07-31'
description: Sonarr is a PVR for Usenet and BitTorrent users.
home: https://github.com/Sonarr/Sonarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/sonarr/icons/icon.png
keywords:
- media
- series
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: sonarr
run_as_context:
- description: Container [sonarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/sonarr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/sonarr/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/sonarr/screenshots/screenshot3.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/sonarr
- https://github.com/Sonarr/Sonarr
title: Sonarr
train: community
version: 1.3.2
