annotations:
  min_scale_version: 24.10.2.2
app_version: 2.6.0
capabilities: []
categories:
- financial
changelog_url: https://github.com/Chia-Network/chia-blockchain/releases
date_added: '2024-08-21'
description: Chia is a modern cryptocurrency built from scratch, designed to be efficient,
  decentralized, and secure.
home: https://www.chia.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/chia/icons/icon.svg
keywords:
- blockchain
- hard-drive
- chia
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: chia
run_as_context:
- description: Container [chia] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/Chia-Network/chia-docker
- https://www.chia.net/
title: Chia
train: community
version: 1.3.1
