annotations:
  min_scale_version: 24.10.2.2
app_version: 1.35.3
capabilities: []
categories:
- security
changelog_url: https://github.com/dani-garcia/vaultwarden/releases
date_added: '2024-09-19'
description: Alternative implementation of the Bitwarden server API written in Rust
  and compatible with upstream Bitwarden clients.
home: https://github.com/dani-garcia/vaultwarden
host_mounts: []
icon: https://media.sys.truenas.net/apps/vaultwarden/icons/icon.svg
keywords:
- password
- manager
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: vaultwarden
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [vaultwarden] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/vaultwarden/screenshots/screenshot1.png
sources:
- https://github.com/dani-garcia/vaultwarden
title: Vaultwarden
train: community
version: 1.5.0
