app_version: '356'
capabilities: []
categories:
- management
changelog_url: https://cockpit-project.org/blog/category/release.html
date_added: '2025-03-21'
description: Cockpit is a web-based graphical interface for Linux servers.
home: https://cockpit-project.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/cockpit-ws/icons/icon.png
keywords:
- cockpit
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cockpit-ws
run_as_context:
- description: Container [cockpit] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://quay.io/repository/cockpit/ws
title: Cockpit WS
train: community
version: 1.1.3
