annotations:
  min_scale_version: 24.10.2.2
app_version: 1.2.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/benbusby/whoogle-search/releases
date_added: '2024-08-09'
description: Whoogle is a self-hosted, ad-free, privacy-respecting metasearch engine
home: https://github.com/benbusby/whoogle-search
host_mounts: []
icon: https://media.sys.truenas.net/apps/whoogle/icons/icon.png
keywords:
- search
- engine
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: whoogle
run_as_context:
- description: Container [whoogle] runs as non-root user and group.
  gid: 927
  group_name: Host group is [unknown (927)]
  uid: 927
  user_name: Host user is [unknown (927)]
screenshots:
- https://media.sys.truenas.net/apps/whoogle/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/whoogle/screenshots/screenshot2.png
sources:
- https://github.com/benbusby/whoogle-search
- https://hub.docker.com/r/benbusby/whoogle-search
title: Whoogle
train: community
version: 1.3.1
