annotations:
  min_scale_version: 24.10.2.2
app_version: 4.12.6
capabilities: []
categories:
- media
changelog_url: https://github.com/jesec/flood/releases
date_added: '2025-03-10'
description: A modern web UI for various torrent clients with a Node.js backend and
  React frontend.
home: https://flood.js.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/flood/icons/icon.png
keywords:
- torrent
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: flood
run_as_context:
- description: Container [flood] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/flood/screenshots/screenshot1.png
sources:
- https://github.com/jesec/flood
- https://hub.docker.com/r/jesec/flood
title: Flood
train: community
version: 1.2.2
