annotations:
  min_scale_version: 24.10.2.2
app_version: 4.9.4.1
capabilities:
- description: Emby is able to change file ownership arbitrarily
  name: CHOWN
- description: Emby is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Emby is able to bypass permission checks for file operations
  name: FOWNER
- description: Emby is able to send signals to any process
  name: KILL
- description: Emby is able to change group ID of processes
  name: SETGID
- description: Emby is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/MediaBrowser/Emby.Releases/releases/
date_added: '2024-08-02'
description: Emby is designed to help you manage your personal media library, such
  as home videos and photos
home: https://emby.media/
host_mounts: []
icon: https://media.sys.truenas.net/apps/emby/icons/icon.png
keywords:
- emby
- media
- entertainment
- movies
- series
- tv
- streaming
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: emby
run_as_context:
- description: Container [emby] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/emby/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/emby/screenshots/screenshot2.png
sources:
- https://emby.media/
- https://hub.docker.com/r/emby/embyserver
title: Emby Server
train: stable
version: 1.4.2
