annotations:
  min_scale_version: 24.10.2.2
app_version: 1.5.0
capabilities:
- description: Dockge is able to change file ownership arbitrarily
  name: CHOWN
- description: Dockge is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Dockge is able to bypass permission checks for file operations
  name: FOWNER
- description: Dockge is able to send signals to any process
  name: KILL
- description: Dockge is able to set file capabilities on other files
  name: SETFCAP
- description: Dockge is able to change group ID of processes
  name: SETGID
- description: Dockge is able to transfer capabilities between processes
  name: SETPCAP
- description: Dockge is able to change user ID of processes
  name: SETUID
categories:
- management
changelog_url: https://github.com/louislam/dockge/releases
date_added: '2024-08-01'
description: A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented
  manager
home: https://dockge.kuma.pet
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/dockge/icons/icon.svg
keywords:
- docker
- compose
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dockge
run_as_context:
- description: Container [dockge] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/dockge/screenshots/screenshot1.png
sources:
- https://dockge.kuma.pet
- https://github.com/louislam/dockge
title: Dockge
train: community
version: 1.3.1
