app_version: 1.0.0-alpha.83
capabilities: []
categories:
- storage
changelog_url: https://github.com/rustfs/rustfs/releases
date_added: '2025-11-07'
description: RustFS is an open-source, S3-compatible high-performance object storage
  system supporting migration and coexistence with other S3-compatible platforms such
  as MinIO and Ceph.
home: https://rustfs.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/rustfs/icons/icon.svg
keywords:
- s3
- storage
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rustfs
run_as_context:
- description: Container [rustfs] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/RustFS/RustFS
- https://hub.docker.com/r/rustfs/rustfs
title: RustFS
train: community
version: 1.1.0
