app_version: latest
capabilities:
- description: Channels DVR is able to use chroot() system call
  name: SYS_CHROOT
categories:
- media
date_added: '2025-05-06'
description: Watch and record your favorite shows and movies from every TV and device.
  From your living room, second home, hotel room, or even on your commute, Channels
  lets you watch your personal media your way.
home: https://getchannels.com/dvr-server/
host_mounts: []
icon: https://media.sys.truenas.net/apps/channels-dvr/icons/icon.svg
keywords:
- channels
- livetv
- streaming
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: channels-dvr
run_as_context:
- description: Container [channels-dvr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/r/fancybits/channels-dvr
title: Channels DVR
train: community
version: 1.1.1
