app_version: 0.11.0
capabilities:
- description: Backend is able to change file ownership arbitrarily
  name: CHOWN
- description: Backend is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Backend is able to bypass permission checks for file operations
  name: FOWNER
- description: Backend is able to change group ID of processes
  name: SETGID
- description: Backend is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/seanmorley15/AdventureLog/releases
date_added: '2025-09-03'
description: Self-hostable travel tracker and trip planner.
home: https://adventurelog.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/adventurelog/icons/icon.svg
keywords:
- adventure
- location
- tracker
- planner
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: adventurelog
run_as_context:
- description: Container [backend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [frontend] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [postgis] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/seanmorley15/AdventureLog
title: AdventureLog
train: community
version: 1.2.1
