app_version: v1.6.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/hargata/lubelog/releases
date_added: '2026-02-04'
description: LubeLogger is a web-based vehicle maintenance and fuel mileage tracker
home: https://lubelogger.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/lubelogger/icons/icon.png
keywords:
- vehicle
- maintenance
- fuel
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: lubelogger
run_as_context:
- description: Container [lubelogger] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/hargata/lubelog
title: LubeLogger
train: community
version: 1.1.1
