app_version: v0.0.28
capabilities: []
categories:
- productivity
changelog_url: https://github.com/timelinize/timelinize/releases
date_added: '2025-10-15'
description: Store your data from all your accounts and devices in a single cohesive
  timeline on your own computer
home: https://timelinize.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/timelinize/icons/icon.svg
keywords:
- media
- timeline
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: timelinize
run_as_context:
- description: Container [timelinize] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/timelinize/timelinize
title: Timelinize
train: community
version: 1.1.0
