annotations:
  min_scale_version: 24.10.2.2
app_version: latest
capabilities: []
categories:
- storage
date_added: '2024-11-08'
description: Filestash is a file manager / web client for SFTP, S3, FTP, WebDAV, Git,
  Minio, LDAP, CalDAV, CardDAV, Mysql, Backblaze, ...
home: https://www.filestash.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/filestash/icons/icon.svg
keywords:
- storage
- file manager
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: filestash
run_as_context:
- description: Container [filestash] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots:
- https://media.sys.truenas.net/apps/filestash/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/filestash/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/filestash/screenshots/screenshot3.png
sources:
- https://www.filestash.app/
- https://github.com/mickael-kerjean/filestash
title: Filestash
train: community
version: 1.2.2
