app_version: 2.5.312
capabilities: []
categories:
- productivity
changelog_url: https://github.com/requarks/wiki/releases
date_added: '2025-08-13'
description: Wiki.js is a modern and powerful wiki app built on Node.js.
home: https://js.wiki/
host_mounts: []
icon: https://media.sys.truenas.net/apps/wiki-js/icons/icon.svg
keywords:
- wiki
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: wiki-js
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [wiki-js] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/requarks/wiki
- https://docs.requarks.io/
title: Wiki.js
train: community
version: 1.2.2
