app_version: 3.13.7
capabilities: []
categories:
- productivity
changelog_url: https://community.teamspeak.com/c/announcements/7
date_added: '2025-05-26'
description: TeamSpeak is software for quality voice communication via the Internet.
home: https://teamspeak.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/teamspeak/icons/icon.svg
keywords:
- voice
- audio
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: teamspeak
run_as_context:
- description: Container [teamspeak] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/_/teamspeak
title: Teamspeak
train: community
version: 1.1.1
