app_version: 4.6.1
capabilities: []
categories:
- games
changelog_url: https://github.com/rommapp/romm/releases
date_added: '2025-01-14'
description: RomM allows you to scan, enrich, browse and play your game collection
  with a clean and responsive interface. With support for multiple platforms, various
  naming schemes, and custom tags, RomM is a must-have for anyone who plays on emulators.
home: https://romm.app
host_mounts: []
icon: https://media.sys.truenas.net/apps/romm/icons/icon.png
keywords:
- romm
- rom
- manager
- emulator
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: romm
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [romm] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/romm/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/romm/screenshots/screenshot2.png
sources:
- https://github.com/rommapp/romm
title: RomM
train: community
version: 1.2.0
