app_version: v3.11.0
capabilities: []
categories:
- ai
changelog_url: https://github.com/mudler/LocalAI/releases
date_added: '2025-10-30'
description: The free, Open Source alternative to OpenAI, Claude and others. Self-hosted
  and local-first.
home: https://localai.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/localai/icons/icon.png
keywords:
- ai
- llm
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: localai
run_as_context:
- description: Container [localai] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/ollama/ollama
title: LocalAI
train: community
version: 1.1.0
