app_version: 0.9.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/MansiVisuals/ViTransfer/releases
date_added: '2025-11-07'
description: ViTransfer - Professional video review and approval platform for filmmakers
home: https://www.vitransfer.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/vitransfer/icons/icon.svg
keywords:
- video
- feedback
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: vitransfer
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [vitransfer] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [worker] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/MansiVisuals/ViTransfer
- https://www.vitransfer.com
title: ViTransfer
train: community
version: 1.1.0
