app_version: 6.3.3.1
capabilities: []
categories:
- games
changelog_url: https://github.com/JustArchiNET/ArchiSteamFarm/releases
date_added: '2025-03-31'
description: ArchiSteamFarm is a tool for automatically farming Steam trading cards
  on multiple accounts simultaneously
home: https://github.com/JustArchiNET/ArchiSteamFarm
host_mounts: []
icon: https://media.sys.truenas.net/apps/archisteamfarm/icons/icon.webp
keywords:
- archisteamfarm
- steam
- asf
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: archisteamfarm
run_as_context:
- description: Container [archisteamfarm] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/JustArchiNET/ArchiSteamFarm/
title: ArchiSteamFarm
train: community
version: 1.1.3
