app_version: v0.4.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/LogicLabs-OU/OpenArchiver/releases
date_added: '2025-11-04'
description: An open-source platform for legally compliant email archiving.
home: https://openarchiver.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/openarchiver/icons/icon.svg
keywords:
- email
- archiving
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: openarchiver
run_as_context:
- description: Container [meilisearch] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [openarchiver] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [tika] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/r/logiclabshq/open-archiver
- https://github.com/LogicLabs-OU/OpenArchiver
title: OpenArchiver
train: community
version: 1.2.2
