app_version: v26.0
capabilities:
- description: NZBGet is able to change file ownership arbitrarily
  name: CHOWN
- description: NZBGet is able to bypass permission checks for file operations
  name: FOWNER
- description: NZBGet is able to change group ID of processes
  name: SETGID
- description: NZBGet is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/nzbgetcom/nzbget/blob/develop/ChangeLog.md
date_added: '2025-03-12'
description: NZBGet is a binary downloader, which downloads files from Usenet based-on
  information given in nzb files.
home: https://nzbget.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/nzbget/icons/icon.svg
keywords:
- media
- usenet
- newsreader
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: nzbget
run_as_context:
- description: Container [nzbget] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot3.png
sources:
- https://github.com/nzbgetcom/nzbget
title: NZBGet
train: community
version: 1.1.2
