annotations:
  min_scale_version: 24.10.2.2
app_version: 1.3.3
capabilities: []
categories:
- custom
date_added: '2024-09-10'
description: An application for deploying simple containers.
home: https://www.truenas.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-app/icons/icon.webp
keywords: []
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ix-app
run_as_context: []
screenshots: []
sources: []
title: iX App
train: stable
version: 1.3.4
