app_version: v1.0.18
capabilities: []
categories:
- management
changelog_url: ''
date_added: '2026-01-21'
description: Dockhand - Docker management you will like.
home: https://dockhand.pro
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/dockhand/icons/icon.webp
keywords:
- docker
- compose
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dockhand
run_as_context:
- description: Container [dockhand] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Finsys/dockhand
- https://hub.docker.com/r/fnsys/dockhand
title: Dockhand
train: community
version: 1.1.3
