app_version: 0.31.0
capabilities:
- description: Karakeep is able to change file ownership arbitrarily
  name: CHOWN
- description: Karakeep is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Karakeep is able to bypass permission checks for file operations
  name: FOWNER
categories:
- productivity
changelog_url: https://github.com/karakeep-app/karakeep/releases
date_added: '2025-04-07'
description: Karakeep is a self-hostable bookmark-everything app (links, notes and
  images) with AI-based automatic tagging and full text search
home: https://karakeep.app
host_mounts: []
icon: https://media.sys.truenas.net/apps/karakeep/icons/icon.svg
keywords:
- hoarder
- bookmarks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: karakeep
run_as_context:
- description: Container [chrome] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [karakeep] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [meilisearch] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/karakeep/screenshots/screenshot1.png
sources:
- https://github.com/karakeep-app/karakeep
- https://karakeep.app/
title: Karakeep
train: community
version: 1.2.2
