app_version: 1.5.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/outline/outline/releases
date_added: '2025-03-31'
description: Outline is the fastest knowledge base for growing teams. Beautiful, realtime
  collaborative, feature packed, and markdown compatible.
home: https://www.getoutline.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/outline/icons/icon.png
keywords:
- documentation
- knowledgebase
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: outline
run_as_context:
- description: Container [outline] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://docs.getoutline.com/s/hosting
- https://github.com/outline/outline
title: Outline
train: community
version: 1.2.2
