app_version: 4.0.3
capabilities: []
categories:
- storage
changelog_url: https://github.com/opencloud-eu/opencloud/releases
date_added: '2025-09-17'
description: Excellent file management and collaboration for public authorities, providers
  and business - or anyone who values ease of use and digital sovereignty.
home: https://opencloud.eu
host_mounts: []
icon: https://media.sys.truenas.net/apps/opencloud/icons/icon.svg
keywords:
- file sharing
- collaboration
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: opencloud
run_as_context:
- description: Container [opencloud] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [radicale] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [tika] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://docs.opencloud.eu/
- https://github.com/OpenCloud/OpenCloud
- https://hub.docker.com/r/opencloudeu/opencloud
title: OpenCloud
train: community
version: 1.2.2
