app_version: 2.5.1
capabilities:
- description: Stirling PDF is able to change file ownership arbitrarily
  name: CHOWN
- description: Stirling PDF is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Stirling PDF is able to bypass permission checks for file operations
  name: FOWNER
- description: Stirling PDF is able to change group ID of processes
  name: SETGID
- description: Stirling PDF is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/Stirling-Tools/Stirling-PDF/releases
date_added: '2025-02-24'
description: '#1 Locally hosted web application that allows you to perform various
  operations on PDF files'
home: https://www.stirlingpdf.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/stirling-pdf/icons/icon.svg
keywords:
- pdf
- pdf-editor
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: stirling-pdf
run_as_context:
- description: Container [stirling-pdf] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/stirling-pdf/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/stirling-pdf/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/stirling-pdf/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/stirling-pdf/screenshots/screenshot4.png
sources:
- https://github.com/Stirling-Tools/Stirling-PDF
- https://docs.stirlingpdf.com/
title: Stirling PDF
train: community
version: 1.1.3
