annotations:
  min_scale_version: 24.10.2.2
app_version: 5.2.7
capabilities:
- description: Tiny Media Manager is able to change file ownership arbitrarily
  name: CHOWN
- description: Tiny Media Manager is able to change group ID of processes
  name: SETGID
- description: Tiny Media Manager is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://www.tinymediamanager.org/categories/#release
date_added: '2024-09-18'
description: Tiny Media Manager is a media management tool written in Java/Swing.
home: https://www.tinymediamanager.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/tiny-media-manager/icons/icon.png
keywords:
- media
- tv-shows
- movies
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tiny-media-manager
run_as_context:
- description: Container [tiny-media-manager] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/tiny-media-manager/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/tiny-media-manager/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/tiny-media-manager/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/tiny-media-manager/screenshots/screenshot4.png
sources:
- https://www.tinymediamanager.org/
- https://hub.docker.com/r/tinymediamanager/tinymediamanager
title: Tiny Media Manager
train: community
version: 1.3.1
