annotations:
  min_scale_version: 24.10.2.2
app_version: v1.10.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/gethomepage/homepage/releases
date_added: '2024-08-02'
description: Homepage is a modern, secure, highly customizable application dashboard.
home: https://gethomepage.dev/
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/homepage/icons/icon.png
keywords:
- dashboard
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: homepage
run_as_context:
- description: Container [homepage] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots:
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot6.png
sources:
- https://gethomepage.dev/
- https://github.com/gethomepage/homepage
title: Homepage
train: community
version: 1.3.1
