app_version: v0.144.1-noble-full
capabilities: []
categories:
- home-automation
changelog_url: https://github.com/koush/scrypted/releases
date_added: '2025-03-11'
description: Scrypted is a high performance video integration and automation platform
home: https://www.scrypted.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/scrypted/icons/icon.png
keywords:
- video
- automation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: scrypted
run_as_context:
- description: Container [scrypted] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/koush/scrypted
title: Scrypted
train: community
version: 1.1.1
