app_version: v0.28.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/juanfont/headscale/releases
date_added: '2025-06-26'
description: An open source, self-hosted implementation of the Tailscale control server
home: https://github.com/juanfont/headscale/releases
host_mounts: []
icon: https://media.sys.truenas.net/apps/headscale/icons/icon.svg
keywords:
- networking
- tailscale
- vpn
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: headscale
run_as_context:
- description: Container [headscale] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/juanfont/headscale
title: Headscale
train: community
version: 1.1.0
