app_version: 2026.2.0
capabilities: []
categories:
- development
changelog_url: https://github.com/hoppscotch/hoppscotch/releases
date_added: '2025-08-19'
description: Hoppscotch is a lightweight, web-based API development suite.
home: https://hoppscotch.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/hoppscotch/icons/icon.svg
keywords:
- api
- development
- postman
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: hoppscotch
run_as_context:
- description: Container [admin] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [backend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [frontend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://hoppscotch.com
- https://hoppscotch.io
- https://github.com/hoppscotch/hoppscotch
- https://hub.docker.com/r/hoppscotch/hoppscotch-frontend
- https://hub.docker.com/r/hoppscotch/hoppscotch-backend
- https://hub.docker.com/r/hoppscotch/hoppscotch-admin
title: Hoppscotch
train: community
version: 1.2.1
