annotations:
  min_scale_version: 24.10.2.2
app_version: v0.8.5
capabilities: []
categories:
- ai
changelog_url: https://github.com/open-webui/open-webui/releases
date_added: '2024-10-24'
description: Open WebUI is an extensible, feature-rich, and user-friendly self-hosted
  WebUI designed to operate entirely offline. It supports various LLM runners, including
  Ollama and OpenAI-compatible APIs.
home: https://github.com/open-webui/open-webui
host_mounts: []
icon: https://media.sys.truenas.net/apps/open-webui/icons/icon.png
keywords:
- ai
- llm
- webui
- open-webui
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: open-webui
run_as_context:
- description: Container [open-webui] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/open-webui/screenshots/screenshot1.png
sources:
- https://github.com/open-webui/open-webui
title: Open WebUI
train: community
version: 1.3.1
