app_version: v3.0.1
capabilities: []
categories:
- media
changelog_url: https://github.com/seerr-team/seerr/releases
date_added: '2026-02-17'
description: Open-source media request and discovery manager for Jellyfin, Plex, and
  Emby.
home: https://docs.seerr.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/seerr/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: seerr
run_as_context:
- description: Container [seerr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/seerr-team/seerr
title: Seerr
train: community
version: 1.0.2
