app_version: 0.8.1-pg
capabilities:
- description: Mydia is able to change file ownership arbitrarily
  name: CHOWN
- description: Mydia is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Mydia is able to bypass permission checks for file operations
  name: FOWNER
- description: Mydia is able to change group ID of processes
  name: SETGID
- description: Mydia is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/getmydia/mydia/releases
date_added: '2025-12-11'
description: Your personal media companion, built with Phoenix LiveView
home: https://github.com/getmydia/mydia
host_mounts: []
icon: https://media.sys.truenas.net/apps/mydia/icons/icon.svg
keywords:
- media
- manager
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mydia
run_as_context:
- description: Container [mydia] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/getmydia/mydia
title: Mydia
train: community
version: 1.1.1
