app_version: v5.3.1
capabilities:
- description: Shoko Server is able to change file ownership arbitrarily
  name: CHOWN
- description: Shoko Server is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Shoko Server is able to bypass permission checks for file operations
  name: FOWNER
- description: Shoko Server is able to change group ID of processes
  name: SETGID
- description: Shoko Server is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/ShokoAnime/ShokoServer/releases
date_added: '2025-07-08'
description: The All-in-One Cross-Platform Anime Management System Built For You
home: https://shokoanime.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/shoko-server/icons/icon.png
keywords:
- media
- anime
- management
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: shoko-server
run_as_context:
- description: Container [shoko-server] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/ShokoAnime/ShokoServer
title: Shoko Server
train: community
version: 1.1.1
