annotations:
  min_scale_version: 24.10.2.2
app_version: 3.5.2
capabilities: []
categories:
- media
changelog_url: https://github.com/bpatrik/pigallery2/releases
date_added: '2024-09-12'
description: PiGallery2 is a fast directory-first photo gallery website, with rich
  UI, optimized for running on low resource servers
home: https://bpatrik.github.io/pigallery2
host_mounts: []
icon: https://media.sys.truenas.net/apps/pigallery2/icons/icon.png
keywords:
- photo
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: pigallery2
run_as_context:
- description: Container [pigallery] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot6.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot7.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot8.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot9.png
- https://media.sys.truenas.net/apps/pigallery2/screenshots/screenshot10.png
sources:
- https://hub.docker.com/r/bpatrik/pigallery2
- https://github.com/bpatrik/pigallery2
title: PiGallery2
train: community
version: 1.3.2
