annotations:
  min_scale_version: 24.10.2.2
app_version: 1.5.1
capabilities:
- description: ClamAV is able to change file ownership arbitrarily
  name: CHOWN
- description: ClamAV is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: ClamAV is able to bypass permission checks for file operations
  name: FOWNER
- description: ClamAV is able to change group ID of processes
  name: SETGID
- description: ClamAV is able to change user ID of processes
  name: SETUID
categories:
- security
changelog_url: https://github.com/Cisco-Talos/clamav/releases
date_added: '2024-08-01'
description: ClamAV is an open source (GPLv2) anti-virus toolkit.
home: https://www.clamav.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/clamav/icons/icon.png
keywords:
- anti-virus
- clamav
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: clamav
run_as_context:
- description: Container [clamav] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://docs.clamav.net/
- https://www.clamav.net/
title: ClamAV
train: community
version: 1.4.2
