app_version: 3.0.9
capabilities: []
categories:
- productivity
changelog_url: https://github.com/clusterzx/paperless-ai/releases
date_added: '2025-07-09'
description: The most advanced AI companion for Paperless-NGX. Transform your document
  management with powerful AI-driven automation and insights.
home: https://clusterzx.github.io/paperless-ai/
host_mounts: []
icon: https://media.sys.truenas.net/apps/paperless-ai/icons/icon.png
keywords:
- paperless
- ai
- automation
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: paperless-ai
run_as_context:
- description: Container [paperless] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/clusterzx/paperless-ai
- https://github.com/clusterzx/paperless-ai
title: Paperless AI
train: community
version: 1.1.0
