app_version: 0.1.4
capabilities: []
categories:
- networking
changelog_url: https://github.com/Lissy93/domain-locker/releases
date_added: '2026-02-26'
description: A self-hosted domain management dashboard. Tracks expiry, DNS records,
  SSL certificates, uptime and WHOIS data for domains you own.
home: https://domain-locker.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/domain-locker/icons/icon.svg
keywords:
- domain
- management
- monitoring
lib_version: 2.2.5
lib_version_hash: 145fa34a11b364877375e15f92c2f527519e2e0dac73aeda60273299925dad65
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: domain-locker
run_as_context:
- description: Container [cron] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [domain-locker] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/Lissy93/domain-locker
- https://ghcr.io/lissy93/domain-locker
- https://hub.docker.com/r/lissy93/domain-locker
title: Domain Locker
train: community
version: 1.0.0
