annotations:
  min_scale_version: 24.10.2.2
app_version: 2026.2.3
capabilities:
- description: Home Assistant is able to change file ownership arbitrarily
  name: CHOWN
- description: Home Assistant is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Home Assistant is able to bypass permission checks for file operations
  name: FOWNER
- description: Home Assistant is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Home Assistant is able to use raw and packet sockets
  name: NET_RAW
categories:
- productivity
changelog_url: https://github.com/home-assistant/core/releases
date_added: '2024-08-13'
description: Home Assistant is an open source home automation that puts local control
  and privacy first.
home: https://www.home-assistant.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/home-assistant/icons/icon.png
keywords:
- home-automation
- assistant
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: home-assistant
run_as_context:
- description: Container [home-assistant] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/home-assistant/screenshots/screenshot1.png
sources:
- https://github.com/home-assistant/home-assistant
title: Home Assistant
train: stable
version: 1.8.3
