app_version: 4.4.2
capabilities: []
categories:
- media
changelog_url: https://github.com/diced/zipline/releases
date_added: '2025-05-19'
description: Zipline The next generation ShareX / File upload server.
home: https://zipline.diced.sh/
host_mounts: []
icon: https://media.sys.truenas.net/apps/zipline/icons/icon.png
keywords:
- zipline
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zipline
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [zipline] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
sources:
- https://github.com/diced/zipline
title: Zipline
train: community
version: 1.1.1
