annotations:
  min_scale_version: 24.10.2.2
app_version: version-6.5.0
capabilities:
- description: Importer is able to change file ownership arbitrarily
  name: CHOWN
- description: Importer is able to bypass permission checks for file operations
  name: FOWNER
- description: Importer is able to change group ID of processes
  name: SETGID
- description: Importer is able to change user ID of processes
  name: SETUID
categories:
- financial
changelog_url: https://docs.firefly-iii.org/references/firefly-iii/changelog/
date_added: '2024-08-13'
description: Firefly III is a personal finances manager
home: https://www.firefly-iii.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/firefly-iii/icons/icon.png
keywords:
- finance
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: firefly-iii
run_as_context:
- description: Container [cron] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
- description: Container [firefly-iii] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
- description: Container [importer] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/firefly-iii/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/firefly-iii/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/firefly-iii/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/firefly-iii/screenshots/screenshot4.png
sources:
- https://hub.docker.com/r/fireflyiii/core/
- https://github.com/firefly-iii/firefly-iii
title: Firefly III
train: community
version: 1.8.3
