app_version: 11.15.4
capabilities: []
categories:
- productivity
changelog_url: https://github.com/directus/directus/releases
date_added: '2025-06-03'
description: Directus is a real-time API and App dashboard for managing SQL database
  content.
home: https://directus.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/directus/icons/icon.svg
keywords:
- directus
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: directus
run_as_context:
- description: Container [directus] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/directus/directus
- https://directus.io/
- https://directus.io/docs/
title: Directus
train: community
version: 1.2.0
