app_version: v3.6.6
capabilities:
- description: Kerberos Agent is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- cameras
changelog_url: https://github.com/kerberos-io/agent/releases
date_added: '2025-02-20'
description: An open and scalable video surveillance system for anyone making this
  world a better and more peaceful place.
home: https://kerberos.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/kerberos-agent/icons/icon.svg
keywords:
- kerberos
- security
- video
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kerberos-agent
run_as_context:
- description: Container [kerberos-agent] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/kerberos-agent/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/kerberos-agent/screenshots/screenshot2.png
sources:
- https://github.com/kerberos-io/agent
title: Kerberos.io Agent
train: community
version: 1.1.1
