app_version: 0.23.1-rootless
capabilities: []
categories:
- management
date_added: '2025-04-24'
description: Homebox is the inventory and organization system built for the Home User!
home: https://homebox.software
host_mounts: []
icon: https://media.sys.truenas.net/apps/homebox/icons/icon.svg
keywords:
- inventory
- organization
- management
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: homebox
run_as_context:
- description: Container [homebox] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/homebox/screenshots/screenshot1.png
sources:
- https://github.com/sysadminsmedia/homebox
- https://homebox.software
title: Homebox
train: community
version: 1.1.0
