app_version: 2.2.0.3-stable
capabilities: []
categories:
- backup
changelog_url: https://github.com/duplicati/duplicati/releases
date_added: '2025-02-12'
description: Store securely encrypted backups in the cloud!
home: http://duplicati.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/duplicati/icons/icon.png
keywords:
- backup
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: duplicati
run_as_context:
- description: Container [duplicati] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/duplicati/duplicati
- https://hub.docker.com/r/duplicati/duplicati
title: Duplicati
train: community
version: 1.1.0
