app_version: v1.13.1
capabilities: []
categories:
- media
changelog_url: https://github.com/autobrr/qui/releases
date_added: '2025-12-24'
description: Modern alternative webUI for qBittorrent, with multi-instance support.
  Written in Go/React.
home: https://github.com/autobrr/qui
host_mounts: []
icon: https://media.sys.truenas.net/apps/qui/icons/icon.svg
keywords:
- media
- qbittorrent
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: qui
run_as_context:
- description: Container [qui] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/autobrr/qui
title: qui
train: community
version: 1.1.2
