app_version: 0.24.1167
capabilities: []
categories:
- media
changelog_url: https://github.com/Jackett/Jackett/releases
date_added: '2025-02-05'
description: API Support for your favorite torrent trackers
home: https://github.com/Jackett/Jackett
host_mounts: []
icon: https://media.sys.truenas.net/apps/jackett/icons/icon.png
keywords:
- indexer
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jackett
run_as_context:
- description: Container [jackett] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Jackett/Jackett
- https://github.com/home-operations/containers/tree/main/apps/jackett
title: Jackett
train: community
version: 1.1.5
