app_version: 0.43.0
capabilities:
- description: Globalping Probe is able to use raw and packet sockets
  name: NET_RAW
categories:
- networking
changelog_url: https://github.com/jsdelivr/globalping-probe/releases
date_added: '2025-12-08'
description: Join the Globalping network to help run distributed network tests like
  ping and traceroute from your location.
home: https://github.com/jsdelivr/globalping-probe
host_mounts: []
icon: https://media.sys.truenas.net/apps/globalping-probe/icons/icon.svg
keywords:
- networking
- monitoring
- ping
- traceroute
- globalping
- probe
- latency
- benchmark
- tools
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: globalping-probe
run_as_context:
- description: Container [globalping-probe] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/jsdelivr/globalping-probe
title: Globalping Probe
train: community
version: 1.1.1
