app_version: v0.29.1
capabilities:
- description: Zerobyte is able to perform system administration operations
  name: SYS_ADMIN
categories:
- storage
changelog_url: https://github.com/nicotsx/zerobyte/releases
date_added: '2025-12-17'
description: Backup automation for self-hosters
home: https://github.com/nicotsx/zerobyte
host_mounts:
- description: Fuse Device
  host_path: /dev/fuse
icon: https://media.sys.truenas.net/apps/zerobyte/icons/icon.svg
keywords:
- backup
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zerobyte
run_as_context:
- description: Container [zerobyte] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/nicotsx/zerobyte
title: Zerobyte
train: community
version: 1.1.5
