app_version: 0.14.0
capabilities: []
categories:
- backup
changelog_url: https://github.com/restic/restic-rest-server/releases
date_added: '2025-08-25'
description: Rest Server is a high performance HTTP server that implements restic's
  REST backend API.
home: https://github.com/restic/rest-server
host_mounts: []
icon: https://media.sys.truenas.net/apps/restic-rest-server/icons/icon.png
keywords:
- backup
- restic
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: restic-rest-server
run_as_context:
- description: Container [restic-server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/restic/rest-server
- https://hub.docker.com/r/restic/rest-server
title: Restic REST Server
train: community
version: 1.1.1
