annotations:
  min_scale_version: 24.10.2.2
app_version: 3.1.2.4902
capabilities: []
categories:
- media
changelog_url: https://github.com/lidarr/Lidarr/releases
date_added: '2024-07-31'
description: Lidarr is a music collection manager for Usenet and BitTorrent users.
home: https://github.com/Lidarr/Lidarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/lidarr/icons/icon.png
keywords:
- media
- music
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: lidarr
run_as_context:
- description: Container [lidarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/lidarr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/lidarr/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/lidarr/screenshots/screenshot3.png
sources:
- https://github.com/Lidarr/Lidarr
- https://github.com/home-operations/containers/tree/main/apps/lidarr
title: Lidarr
train: community
version: 1.4.2
