annotations:
  min_scale_version: 24.10.2.2
app_version: 1.1.15
capabilities: []
categories:
- productivity
changelog_url: https://github.com/rustdesk/rustdesk-server/releases
date_added: '2024-09-13'
description: Rust Desk is an open-source remote desktop, and alternative to TeamViewer.
home: https://rustdesk.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/rust-desk/icons/icon.png
keywords:
- remote
- desktop
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rust-desk
run_as_context:
- description: Container [rust-desk] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [rust-desk-relay] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/r/rustdesk/rustdesk-server
- https://github.com/rustdesk/rustdesk-server
title: Rust Desk
train: community
version: 1.5.0
