app_version: 2.1.3
capabilities:
- description: Baserow is able to change file ownership arbitrarily
  name: CHOWN
- description: Baserow is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Baserow is able to bypass permission checks for file operations
  name: FOWNER
- description: Baserow is able to send signals to any process
  name: KILL
- description: Baserow is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Baserow is able to change group ID of processes
  name: SETGID
- description: Baserow is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://gitlab.com/baserow/baserow/-/releases
date_added: '2025-05-16'
description: Baserow is an open source no-code database and Airtable alternative.
  Create your own database without technical experience. Our user friendly no-code
  tool gives you the powers of a developer without leaving your browser.
home: https://baserow.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/baserow/icons/icon.svg
keywords:
- database
- airtable
- webui
- no-code
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: baserow
run_as_context:
- description: Container [baserow] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://gitlab.com/baserow/baserow
title: Baserow
train: community
version: 1.2.7
