app_version: 4.0.0-beta.463
capabilities:
- description: Coolify is able to change file ownership arbitrarily
  name: CHOWN
- description: Coolify is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Coolify is able to bypass permission checks for file operations
  name: FOWNER
- description: Coolify is able to change group ID of processes
  name: SETGID
- description: Coolify is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/coollabsio/coolify/releases
date_added: '2025-10-08'
description: An open-source & self-hostable Heroku / Netlify / Vercel alternative.
home: https://coolify.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/coolify/icons/icon.svg
keywords:
- self-host
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: coolify
run_as_context:
- description: Container [coolify] runs as non-root user and group.
  gid: 9999
  group_name: Host group is [unknown (9999)]
  uid: 9999
  user_name: Host user is [unknown (9999)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [realtime] runs as non-root user and group.
  gid: 9999
  group_name: Host group is [unknown (9999)]
  uid: 9999
  user_name: Host user is [unknown (9999)]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/coollabsio/coolify
title: Coolify
train: community
version: 1.2.1
