app_version: v2.0.4
capabilities:
- description: BookLore is able to change file ownership arbitrarily
  name: CHOWN
- description: BookLore is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: BookLore is able to bypass permission checks for file operations
  name: FOWNER
- description: BookLore is able to change group ID of processes
  name: SETGID
- description: BookLore is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/booklore-app/booklore/releases
date_added: '2025-09-19'
description: BookLore is a self-hosted app for managing and reading books & comics
  (PDF, EPUB, CBZ) with metadata editing, OPDS, reading progress, and multi-user support.
home: https://github.com/booklore-app/booklore
host_mounts: []
icon: https://media.sys.truenas.net/apps/booklore/icons/icon.svg
keywords:
- media
- ebooks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: booklore
run_as_context:
- description: Container [booklore] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/booklore-app/booklore
title: BookLore
train: community
version: 1.2.4
