app_version: 1.12.3
capabilities: []
categories:
- media
changelog_url: https://github.com/maxdorninger/MediaManager/releases
date_added: '2025-12-10'
description: A modern selfhosted media management system for your media library
home: https://maxdorninger.github.io/MediaManager/introduction.html
host_mounts: []
icon: https://media.sys.truenas.net/apps/media-manager/icons/icon.svg
keywords:
- media
- manager
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: media-manager
run_as_context:
- description: Container [media-manager] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/maxdorninger/MediaManager
title: Media Manager
train: community
version: 1.1.0
