app_version: 1.4.1
capabilities: []
categories:
- media
date_added: '2024-08-08'
description: Plex Auto Languages offer automated language selection for Plex TV Shows
home: https://github.com/JourneyDocker/Plex-Auto-Languages
host_mounts: []
icon: https://media.sys.truenas.net/apps/plex-auto-languages/icons/icon.svg
keywords:
- plex
- languages
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: plex-auto-languages
run_as_context:
- description: Container [plex-auto-languages] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/JourneyDocker/Plex-Auto-Languages
title: Plex Auto Languages
train: community
version: 1.4.1
