app_version: v2.2.2
capabilities:
- description: Next Explorer is able to change file ownership arbitrarily
  name: CHOWN
- description: Next Explorer is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Next Explorer is able to bypass permission checks for file operations
  name: FOWNER
- description: Next Explorer is able to change group ID of processes
  name: SETGID
- description: Next Explorer is able to change user ID of processes
  name: SETUID
categories:
- storage
changelog_url: https://github.com/vikramsoni2/nextExplorer/releases
date_added: '2025-11-14'
description: A modern, self-hosted file explorer with secure access control, polished
  UX, and a Docker-friendly deployment story.
home: https://github.com/vikramsoni2/nextExplorer
host_mounts: []
icon: https://media.sys.truenas.net/apps/next-explorer/icons/icon.svg
keywords:
- file explorer
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: next-explorer
run_as_context:
- description: Container [next-explorer] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/vikramsoni2/nextExplorer
title: Next Explorer
train: community
version: 1.1.1
