annotations:
  min_scale_version: 24.10.2.2
app_version: 2.10-SNAPSHOT-ocr-es7
capabilities: []
categories:
- productivity
changelog_url: https://fscrawler.readthedocs.io/en/latest/release/index.html
date_added: '2024-08-06'
description: FSCrawler is a crawler that helps to index binary documents such as PDF,
  Open Office, MS Office.
home: https://fscrawler.readthedocs.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/fscrawler/icons/icon.svg
keywords:
- index
- crawler
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: fscrawler
run_as_context:
- description: Container [fscrawler] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/dadoonet/fscrawler
- https://hub.docker.com/r/dadoonet/fscrawler
- https://fscrawler.readthedocs.io/
title: FSCrawler
train: community
version: 1.3.1
