app_version: 3.0.3
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/umami-software/umami/releases
date_added: '2025-01-10'
description: Umami is a simple, fast, privacy-focused alternative to Google Analytics.
home: https://umami.is/
host_mounts: []
icon: https://media.sys.truenas.net/apps/umami/icons/icon.svg
keywords:
- analytics
- monitoring
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: umami
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [umami] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
screenshots:
- https://media.sys.truenas.net/apps/umami/screenshots/screenshot1.jpg
sources:
- https://github.com/umami-software/umami
title: Umami
train: community
version: 1.2.2
