app_version: 0.4.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/mostafa-wahied/autoxpose/releases
date_added: '2026-02-11'
description: Automatic DNS and reverse proxy configuration for Docker containers.
home: https://github.com/mostafa-wahied/autoxpose
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/autoxpose/icons/icon.svg
keywords:
- dns
- reverse-proxy
- docker
- automation
- networking
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: autoxpose
run_as_context:
- description: Container [autoxpose] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/autoxpose/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/autoxpose/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/autoxpose/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/autoxpose/screenshots/screenshot4.png
sources:
- https://github.com/mostafa-wahied/autoxpose
- https://hub.docker.com/r/mostafawahied/autoxpose
title: autoxpose
train: community
version: 1.1.2
