annotations:
  min_scale_version: 24.10.2.2
app_version: 1.24.1
capabilities: []
categories:
- media
changelog_url: https://github.com/gotson/komga/blob/master/CHANGELOG.md
date_added: '2024-08-02'
description: Komga is a free and open source comics/mangas server.
home: https://komga.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/komga/icons/icon.svg
keywords:
- media
- comics
- mangas
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: komga
run_as_context:
- description: Container [komga] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/komga/screenshots/screenshot1.png
sources:
- https://github.com/gotson/komga
- https://hub.docker.com/r/gotson/komga
title: Komga
train: community
version: 1.4.2
