app_version: 1.1.57
capabilities: []
categories:
- productivity
changelog_url: https://github.com/Ylianst/MeshCentral/releases
date_added: '2025-10-01'
description: A complete web-based remote monitoring and management web site. Once
  setup you can install agents and perform remote desktop session to devices on the
  local network or over the Internet.
home: https://meshcentral.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/meshcentral/icons/icon.png
keywords:
- remote
- desktop
- remote-desktop
- remote-access
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: meshcentral
run_as_context:
- description: Container [meshcentral] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/Ylianst/MeshCentral
title: MeshCentral
train: community
version: 1.2.2
