app_version: '26.01'
capabilities:
- description: FileFlows is able to write records to audit log
  name: AUDIT_WRITE
- description: FileFlows is able to change file ownership arbitrarily
  name: CHOWN
- description: FileFlows is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: FileFlows is able to bypass permission checks for file operations
  name: FOWNER
- description: FileFlows is able to change group ID of processes
  name: SETGID
- description: FileFlows is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://fileflows.com/docs/versions
date_added: '2025-09-11'
description: FileFlows automates all file types - videos, audio, images, books - with
  VMAF-optimized AV1 and HEVC transcoding for top-tier quality.
home: https://fileflows.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/fileflows/icons/icon.svg
keywords:
- encode
- transcode
- audio
- images
- automate
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: fileflows
run_as_context:
- description: Container [fileflows] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/fileflows/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/fileflows/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/fileflows/screenshots/screenshot3.png
sources:
- https://fileflows.com/
- https://hub.docker.com/r/revenz/fileflows
title: FileFlows
train: community
version: 1.1.2
