app_version: 1.4.18
capabilities: []
categories:
- media
changelog_url: https://github.com/connorgallopo/tracearr/releases
date_added: '2025-12-22'
description: Tracearr is a streaming access manager for Plex, Jellyfin and Emby servers.
home: https://github.com/connorgallopo/tracearr
host_mounts: []
icon: https://media.sys.truenas.net/apps/tracearr/icons/icon.svg
keywords:
- plex
- jellyfin
- emby
- streaming
- media
- account sharing
- session
- geolocation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tracearr
run_as_context:
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [timescale] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [tracearr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/tracearr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/tracearr/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/tracearr/screenshots/screenshot3.png
sources:
- https://github.com/connorgallopo/tracearr
title: Tracearr
train: community
version: 1.2.1
