app_version: 2.8.0
capabilities:
- description: Zigbee2MQTT is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- home-automation
changelog_url: https://github.com/Koenkk/zigbee2mqtt/blob/master/CHANGELOG.md
date_added: '2024-12-24'
description: Zigbee to MQTT bridge get rid of your proprietary Zigbee bridges
home: https://www.zigbee2mqtt.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/zigbee2mqtt/icons/icon.svg
keywords:
- zigbee
- mqtt
- bridge
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zigbee2mqtt
run_as_context:
- description: Container [zigbee2mqtt] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/zigbee2mqtt/screenshots/screenshot1.png
sources:
- https://github.com/Koenkk/zigbee2mqtt
title: Zigbee2MQTT
train: community
version: 1.1.1
