app_version: 2.22.1
capabilities:
- description: Automatic Ripping Machine is able to change file ownership arbitrarily
  name: CHOWN
- description: Automatic Ripping Machine is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Automatic Ripping Machine is able to bypass permission checks for file
    operations
  name: FOWNER
- description: Automatic Ripping Machine is able to change group ID of processes
  name: SETGID
- description: Automatic Ripping Machine is able to change user ID of processes
  name: SETUID
- description: Automatic Ripping Machine is able to perform system administration
    operations
  name: SYS_ADMIN
categories:
- media
changelog_url: https://github.com/automatic-ripping-machine/automatic-ripping-machine/releases
date_added: '2025-05-22'
description: Insert an optical disc (Blu-ray, DVD, CD) and checks to see if it's audio,
  video (Movie or TV), or data, then rips it.
home: https://github.com/automatic-ripping-machine/automatic-ripping-machine
host_mounts: []
icon: https://media.sys.truenas.net/apps/automatic-ripping-machine/icons/icon.png
keywords:
- media
- video
- ripping
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: automatic-ripping-machine
run_as_context:
- description: Container [automatic-ripping-machine] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/automatic-ripping-machine/automatic-ripping-machine
- https://hub.docker.com/r/automaticrippingmachine/automatic-ripping-machine
title: Automatic Ripping Machine
train: community
version: 1.1.3
