app_version: v0.7.52
capabilities:
- description: Retrom is able to change file ownership arbitrarily
  name: CHOWN
- description: Retrom is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Retrom is able to bypass permission checks for file operations
  name: FOWNER
- description: Retrom is able to change group ID of processes
  name: SETGID
- description: Retrom is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/JMBeresford/retrom/releases
date_added: '2025-09-25'
description: A centralized game library/collection management service with a focus
  on emulation
home: https://github.com/JMBeresford/retrom
host_mounts: []
icon: https://media.sys.truenas.net/apps/retrom/icons/icon.png
keywords:
- media
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: retrom
run_as_context:
- description: Container [retrom] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/JMBeresford/retrom
title: Retrom
train: community
version: 1.1.0
