app_version: apache-2.50.0
capabilities:
- description: Kimai is able to change file ownership arbitrarily
  name: CHOWN
- description: Kimai is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Kimai is able to bypass permission checks for file operations
  name: FOWNER
- description: Kimai is able to change group ID of processes
  name: SETGID
- description: Kimai is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/kimai/kimai/releases
date_added: '2025-08-06'
description: Kimai is a web-based multi-user time-tracking application.
home: https://www.kimai.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/kimai/icons/icon.svg
keywords:
- time-tracking
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kimai
run_as_context:
- description: Container [kimai] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://hub.docker.com/r/kimai/kimai2
title: Kimai
train: community
version: 1.2.1
