app_version: 0.3.0
capabilities: []
categories:
- productivity
changelog_url: https://gitea.com/gitea/act_runner/releases
date_added: '2025-01-15'
description: A runner for Gitea based on act.
home: https://gitea.com
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/gitea-act-runner/icons/icon.svg
keywords:
- gitea
- actions
- runner
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gitea-act-runner
run_as_context:
- description: Container [gitea-act-runner] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://docs.gitea.com/usage/actions/act-runner
- https://hub.docker.com/r/gitea/act_runner
- https://gitea.com/gitea/act_runner
title: Gitea Act Runner
train: community
version: 1.1.3
