annotations:
  min_scale_version: 24.10.2.2
app_version: 0.8.9
capabilities:
- description: Kavita is able to change file ownership arbitrarily
  name: CHOWN
- description: Kavita is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Kavita is able to bypass permission checks for file operations
  name: FOWNER
- description: Kavita is able to change group ID of processes
  name: SETGID
- description: Kavita is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/Kareadita/Kavita/releases
date_added: '2024-08-02'
description: Kavita is a fast, feature rich, cross platform reading server.
home: https://www.kavitareader.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/kavita/icons/icon.png
keywords:
- ebook
- manga
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kavita
run_as_context:
- description: Container [kavita] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/kavita/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/kavita/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/kavita/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/kavita/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/kavita/screenshots/screenshot5.png
sources:
- https://github.com/Kareadita/Kavita
- https://www.kavitareader.com
title: Kavita
train: community
version: 1.3.1
