app_version: release-1.11.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/Termix-SSH/Termix/releases
date_added: '2026-02-07'
description: Termix is a web-based server management platform with SSH terminal, tunneling,
  and file editing capabilities.
home: https://termix.site/
host_mounts: []
icon: https://media.sys.truenas.net/apps/termix/icons/icon.svg
keywords:
- ssh
- terminal
- server
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: termix
run_as_context:
- description: Container [termix] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/Termix-SSH/Termix
title: Termix
train: community
version: 1.1.0
