app_version: v0.15.5
capabilities: []
categories:
- productivity
changelog_url: https://github.com/stalwartlabs/stalwart/releases
date_added: '2026-01-23'
description: All-in-one Mail & Collaboration server. Secure, scalable and fluent in
  every protocol (IMAP, JMAP, SMTP, CalDAV, CardDAV, WebDAV).
home: https://stalw.art/
host_mounts: []
icon: https://media.sys.truenas.net/apps/stalwart/icons/icon.svg
keywords:
- mail
- collaboration
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: stalwart
run_as_context:
- description: Container [stalwart] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/stalwartlabs/stalwart
- https://stalw.art/docs/install/platform/docker
title: Stalwart
train: community
version: 1.1.0
