annotations:
  min_scale_version: 24.10.2.2
app_version: 4.1.1
capabilities:
- description: Transmission is able to change file ownership arbitrarily
  name: CHOWN
- description: Transmission is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Transmission is able to bypass permission checks for file operations
  name: FOWNER
- description: Transmission is able to change group ID of processes
  name: SETGID
- description: Transmission is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/transmission/transmission/releases/
date_added: '2024-09-19'
description: Transmission is designed for easy, powerful use.
home: https://transmissionbt.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/transmission/icons/icon.svg
keywords:
- media
- torrent
- download
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: transmission
run_as_context:
- description: Container [transmission] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://docs.linuxserver.io/images/docker-transmission/#parameters
- https://transmissionbt.com/
- https://github.com/linuxserver/docker-transmission
title: Transmission
train: community
version: 1.3.3
