app_version: 1.4.2
capabilities:
- description: Fireshare is able to change file ownership arbitrarily
  name: CHOWN
- description: Fireshare is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Fireshare is able to bypass permission checks for file operations
  name: FOWNER
- description: Fireshare is able to change group ID of processes
  name: SETGID
- description: Fireshare is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/ShaneIsrael/fireshare/releases
date_added: '2025-05-24'
description: Share your game clips, videos, or other media via unique links.
home: https://github.com/ShaneIsrael/fireshare
host_mounts: []
icon: https://media.sys.truenas.net/apps/fireshare/icons/icon.png
keywords:
- file-sharing
- video-sharing
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: fireshare
run_as_context:
- description: Container [fireshare] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/fireshare/screenshots/screenshot1.png
sources:
- https://github.com/ShaneIsrael/fireshare
- https://hub.docker.com/r/shaneisrael/fireshare
title: Fireshare
train: community
version: 1.1.0
