app_version: 0.6.26
capabilities:
- description: Calibre Web is able to change file ownership arbitrarily
  name: CHOWN
- description: Calibre Web is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Calibre Web is able to bypass permission checks for file operations
  name: FOWNER
- description: Calibre Web is able to change group ID of processes
  name: SETGID
- description: Calibre Web is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/janeczku/calibre-web/releases
date_added: '2024-11-13'
description: Calibre Web is a web app for browsing, reading and downloading eBooks
  stored in a Calibre database
home: https://github.com/janeczku/calibre-web
host_mounts: []
icon: https://media.sys.truenas.net/apps/calibre-web/icons/icon.svg
keywords:
- media
- ebooks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: calibre-web
run_as_context:
- description: Container [calibre-web] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/calibre-web/screenshots/screenshot1.png
sources:
- https://github.com/linuxserver/docker-calibre-web
- https://github.com/janeczku/calibre-web
title: Calibre Web
train: community
version: 2.1.1
