annotations:
  min_scale_version: 24.10.2.2
app_version: v0.107.71
capabilities:
- description: Adguard is able to change file ownership arbitrarily
  name: CHOWN
- description: Adguard is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Adguard is able to bypass permission checks for file operations
  name: FOWNER
- description: Adguard is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Adguard is able to use raw and packet sockets
  name: NET_RAW
categories:
- networking
changelog_url: https://github.com/AdguardTeam/AdGuardHome/releases
date_added: '2024-08-01'
description: Free and open source, powerful network-wide ads & trackers blocking DNS
  server.
home: https://github.com/AdguardTeam/AdGuardHome
host_mounts: []
icon: https://media.sys.truenas.net/apps/adguard-home/icons/icon.svg
keywords:
- dns
- adblock
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: adguard-home
run_as_context:
- description: Container [adguard] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/adguard-home/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/adguard-home/screenshots/screenshot2.png
sources:
- https://github.com/AdguardTeam/AdGuardHome
- https://hub.docker.com/r/adguard/adguardhome
title: AdGuard Home
train: community
version: 1.3.2
