app_version: 25.3.5
capabilities: []
categories:
- database
changelog_url: https://github.com/dbeaver/cloudbeaver/releases
date_added: '2025-07-09'
description: CloudBeaver is a Cloud Database Manager.
home: https://dbeaver.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/cloudbeaver/icons/icon.svg
keywords:
- cloudbeaver
- database
- dbeaver
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cloudbeaver
run_as_context:
- description: Container [cloudbeaver] runs as non-root user and group.
  gid: 8978
  group_name: Host group is [unknown (8978)]
  uid: 8978
  user_name: Host user is [unknown (8978)]
screenshots: []
sources:
- https://hub.docker.com/r/dbeaver/cloudbeaver
- https://github.com/dbeaver/cloudbeaver
title: CloudBeaver
train: community
version: 1.1.2
