app_version: v1.11.2
capabilities: []
categories:
- backup
changelog_url: https://github.com/garethgeorge/backrest/releases
date_added: '2026-01-22'
description: Backrest is a web UI and orchestrator for restic backup.
home: https://github.com/garethgeorge/backrest
host_mounts: []
icon: https://media.sys.truenas.net/apps/backrest/icons/icon.svg
keywords:
- backup
- restic
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: backrest
run_as_context:
- description: Container [backrest] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/garethgeorge/backrest
title: Backrest
train: community
version: 1.1.1
