app_version: 2.1.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/ThePhaseless/Byparr/releases
date_added: '2025-07-15'
description: Byparr is a FlareSolverr drop-in replacement with FastAPI and nodriver
home: https://github.com/ThePhaseless/Byparr
host_mounts: []
icon: https://media.sys.truenas.net/apps/byparr/icons/icon.png
keywords:
- networking
- captcha
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: byparr
run_as_context:
- description: Container [byparr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/ThePhaseless/Byparr
title: Byparr
train: community
version: 1.1.1
