annotations:
  min_scale_version: 24.10.2.2
app_version: v2.9.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/qdm12/ddns-updater/releases
date_added: '2024-08-01'
description: Lightweight universal DDNS Updater with web UI
home: https://github.com/qdm12/ddns-updater
host_mounts: []
icon: https://media.sys.truenas.net/apps/ddns-updater/icons/icon.svg
keywords:
- ddns-updater
- ddns
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ddns-updater
run_as_context:
- description: Container [ddns] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/ddns-updater/screenshots/screenshot1.png
sources:
- https://github.com/qdm12/ddns-updater
- https://hub.docker.com/r/qmcgaw/ddns-updater
title: DDNS Updater
train: community
version: 1.3.0
