app_version: 4.109.2
capabilities:
- description: Code Server is able to write records to audit log
  name: AUDIT_WRITE
- description: Code Server is able to change file ownership arbitrarily
  name: CHOWN
- description: Code Server is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Code Server is able to bypass permission checks for file operations
  name: FOWNER
- description: Code Server is able to change group ID of processes
  name: SETGID
- description: Code Server is able to change user ID of processes
  name: SETUID
categories:
- development
changelog_url: https://github.com/coder/code-server/blob/main/CHANGELOG.md
date_added: '2025-04-03'
description: Code Server is VS Code in the browser
home: https://coder.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/code-server/icons/icon.png
keywords:
- code
- editor
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: code-server
run_as_context:
- description: Container [code-server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/coder/code-server
title: Code Server
train: community
version: 1.1.1
