app_version: v1.58.2-noble
capabilities: []
categories:
- development
changelog_url: https://github.com/microsoft/playwright/releases
date_added: '2025-04-23'
description: Playwright enables reliable end-to-end testing for modern web apps.
home: https://playwright.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/playwright/icons/icon.svg
keywords:
- development
- testing
- automation
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: playwright
run_as_context:
- description: Container [playwright] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/playwright/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/playwright/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/playwright/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/playwright/screenshots/screenshot4.png
sources:
- https://playwright.dev/docs/test-ui-mode
- https://playwright.dev/docs/docker
- https://mcr.microsoft.com/en-us/artifact/mar/playwright
title: Playwright
train: community
version: 1.1.1
