app_version: v0.11.0
capabilities: []
categories:
- financial
changelog_url: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md
date_added: '2025-04-24'
description: An efficient re-implementation of Electrum Server in Rust.
home: https://github.com/romanz/electrs/
host_mounts: []
icon: https://media.sys.truenas.net/apps/electrs/icons/icon.svg
keywords:
- bitcoin
- electrum
- cryptocurrency
- blockchain
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: electrs
run_as_context:
- description: Container [electrs] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/romanz/electrs
- https://github.com/getumbrel/docker-electrs
title: Electrs
train: community
version: 1.1.2
