app_version: v1.11.2
capabilities: []
categories:
- media
changelog_url: https://github.com/schlagmichdoch/PairDrop/releases
date_added: '2025-06-24'
description: Transfer Files Cross-Platform. No Setup, No Signup.
home: https://pairdrop.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/pairdrop/icons/icon.png
keywords:
- media
- file transfer
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: pairdrop
run_as_context:
- description: Container [pairdrop] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/schlagmichdoch/PairDrop
title: PairDrop
train: community
version: 1.1.0
