app_version: v1.8.1
capabilities: []
categories:
- storage
changelog_url: https://github.com/huncrys/minio-console/releases
date_added: '2025-06-27'
description: Simple UI for MinIO Object Storage
home: https://github.com/huncrys/minio-console
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio-console/icons/icon.png
keywords:
- minio
- console
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: minio-console
run_as_context:
- description: Container [console] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/minio-console/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/minio-console/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/minio-console/screenshots/screenshot3.png
sources:
- https://github.com/huncrys/minio-console
title: MinIO Console
train: community
version: 1.1.0
