app_version: v2.1.9
capabilities: []
categories:
- media
changelog_url: https://github.com/thomst08/requestrr/releases
date_added: '2025-07-01'
description: Requestrr is a Discord chatbot used to connect users to Sonarr/Radarr/Lidarr/Overseerr/Ombi!
home: https://github.com/thomst08/requestrr
host_mounts: []
icon: https://media.sys.truenas.net/apps/requestrr/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: requestrr
run_as_context:
- description: Container [requestrr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/thomst08/requestrr
- https://hub.docker.com/r/thomst08/requestrr
title: Requestrr
train: community
version: 1.1.2
