annotations:
  min_scale_version: 24.10.2.2
app_version: 0.17.4
capabilities: []
categories:
- ai
changelog_url: https://github.com/ollama/ollama/releases
date_added: '2024-10-24'
description: Get up and running with Llama 3.2, Mistral, Gemma 2, and other large
  language models.
home: https://github.com/ollama/ollama
host_mounts: []
icon: https://media.sys.truenas.net/apps/ollama/icons/icon.png
keywords:
- ai
- llm
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ollama
run_as_context:
- description: Container [ollama] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/ollama/ollama
title: Ollama
train: community
version: 1.2.8
