annotations:
  min_scale_version: 24.10.2.2
app_version: 2026.2.26-c3e3d2d85
capabilities:
- description: SearXNG is able to change group ID of processes
  name: SETGID
- description: SearXNG is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/searxng/searxng/commits/master/
date_added: '2024-09-13'
description: SearXNG is a privacy-respecting, hackable metasearch engine
home: https://github.com/searxng/searxng
host_mounts: []
icon: https://media.sys.truenas.net/apps/searxng/icons/icon.svg
keywords:
- search
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: searxng
run_as_context:
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [searxng] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/searxng/searxng
- https://github.com/searxng/searxng
title: SearXNG
train: community
version: 1.4.4
