app_version: 4.5.0.5
capabilities:
- description: Glances is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Glances is able to bypass permission checks for file operations
  name: FOWNER
- description: Glances is able to change group ID of processes
  name: SETGID
- description: Glances is able to change user ID of processes
  name: SETUID
- description: Glances is able to trace and control other processes
  name: SYS_PTRACE
categories:
- monitoring
changelog_url: https://github.com/nicolargo/glances/releases
date_added: '2025-01-29'
description: Glances is a cross-platform system monitoring tool.
home: https://nicolargo.github.io/glances
host_mounts:
- description: Required to read the OS release information.
  host_path: /etc/os-release
- description: Required to read the processes information.
  host_path: /proc
- description: Required to read the system information.
  host_path: /sys
- description: Required to read the docker information.
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/glances/icons/icon.png
keywords:
- metric
- monitoring
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: glances
run_as_context:
- description: Container [glances] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/glances/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/nicolargo/glances
title: Glances
train: community
version: 1.1.2
