app_version: '0.96'
capabilities:
- description: Signal CLI REST API is able to change file ownership arbitrarily
  name: CHOWN
- description: Signal CLI REST API is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Signal CLI REST API is able to bypass permission checks for file operations
  name: FOWNER
- description: Signal CLI REST API is able to change group ID of processes
  name: SETGID
- description: Signal CLI REST API is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/bbernhard/signal-cli-rest-api/releases
date_added: '2025-11-14'
description: This project creates a small dockerized REST API around signal-cli.
home: https://github.com/bbernhard/signal-cli-rest-api
host_mounts: []
icon: https://media.sys.truenas.net/apps/signal-cli-rest-api/icons/icon.svg
keywords:
- signal
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: signal-cli-rest-api
run_as_context:
- description: Container [signal-cli-rest-api] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/bbernhard/signal-cli-rest-api
title: Signal CLI REST API
train: community
version: 1.1.1
