annotations:
  min_scale_version: 24.10.2.2
app_version: 29.3.6
capabilities: []
categories:
- productivity
changelog_url: https://github.com/jgraph/drawio/blob/dev/ChangeLog
date_added: '2024-08-02'
description: Draw.io is a whiteboarding / diagramming software application.
home: https://www.drawio.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/drawio/icons/icon.png
keywords:
- diagram
- whiteboard
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: drawio
run_as_context:
- description: Container [drawio] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots:
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot3.png
sources:
- https://hub.docker.com/r/jgraph/drawio
- https://github.com/jgraph/drawio
title: Draw.io
train: community
version: 1.4.2
