app_version: 0.3.7
capabilities: []
categories:
- productivity
changelog_url: https://github.com/rustmailer/bichon/releases
date_added: '2025-12-16'
description: Bichon - A lightweight, high-performance Rust email archiver with WebUI
home: https://github.com/rustmailer/bichon
host_mounts: []
icon: https://media.sys.truenas.net/apps/bichon/icons/icon.svg
keywords:
- email
- archiving
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bichon
run_as_context:
- description: Container [bichon] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/rustmailer/bichon
- https://hub.docker.com/r/rustmailer/bichon
title: Bichon
train: community
version: 1.1.1
