app_version: v2.2.0
capabilities: []
categories:
- storage
changelog_url: https://git.deuxfleurs.fr/Deuxfleurs/garage/releases
date_added: '2025-06-05'
description: An open-source distributed object storage service tailored for self-hosting.
home: https://garagehq.deuxfleurs.fr/
host_mounts: []
icon: https://media.sys.truenas.net/apps/garage/icons/icon.svg
keywords:
- garage
- object storage
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: garage
run_as_context:
- description: Container [garage] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [web] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://garagehq.deuxfleurs.fr/
- https://git.deuxfleurs.fr/Deuxfleurs/garage
- https://hub.docker.com/r/dxflrs/garage
- https://github.com/khairul169/garage-webui
title: Garage
train: community
version: 1.1.1
