app_version: '4.12'
capabilities: []
categories:
- storage
changelog_url: https://github.com/seaweedfs/seaweedfs/releases
date_added: '2025-12-18'
description: SeaweedFS is a fast distributed storage system for blobs, objects, files,
  and data lake, for billions of files!
home: https://seaweedfs.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/seaweedfs/icons/icon.png
keywords:
- s3
- webdav
- blob
- object
- bucket
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: seaweedfs
run_as_context:
- description: Container [admin] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [filer] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [master] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [s3] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [volume] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/seaweedfs/seaweedfs
- https://hub.docker.com/r/chrislusf/seaweedfs
title: SeaweedFS
train: stable
version: 1.1.0
