app_version: 1.1.8
capabilities: []
categories:
- media
changelog_url: https://github.com/CyferShepard/Jellystat/releases
date_added: '2025-05-26'
description: Jellystat is a free and open source Statistics App for Jellyfin
home: https://github.com/CyferShepard/Jellystat
host_mounts: []
icon: https://media.sys.truenas.net/apps/jellystat/icons/icon.svg
keywords:
- statistics
- jellyfin
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jellystat
run_as_context:
- description: Container [jellystat] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/jellystat/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/jellystat/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/jellystat/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/jellystat/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/jellystat/screenshots/screenshot5.png
sources:
- https://github.com/CyferShepard/Jellystat
- https://hub.docker.com/r/cyfershepard/jellystat
title: Jellystat
train: community
version: 1.2.2
