app_version: '30.2'
capabilities: []
categories:
- financial
date_added: '2025-04-22'
description: Run your personal node powered by Bitcoin Core.
home: https://bitcoin.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitcoind/icons/icon.png
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bitcoind
run_as_context:
- description: Container [bitcoind] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://bitcoin.org
- https://github.com/sethforprivacy/docker-bitcoind
title: Bitcoin Node
train: community
version: 1.1.0
