app_version: v0.4.2
capabilities: []
categories:
- development
date_added: '2025-07-04'
description: Docker Socket Proxy is a security-enhanced proxy for the Docker Socket.
home: https://github.com/Tecnativa/docker-socket-proxy
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-app/icons/icon.webp
keywords: []
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: docker-socket-proxy
run_as_context:
- description: Container [docker-socket-proxy] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/Tecnativa/docker-socket-proxy
title: Docker Socket Proxy
train: dev
version: 1.1.1
