app_version: 0.10.1.14
capabilities:
- description: Warracker is able to change file ownership arbitrarily
  name: CHOWN
- description: Warracker is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Warracker is able to bypass permission checks for file operations
  name: FOWNER
- description: Warracker is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: Warracker is able to change group ID of processes
  name: SETGID
- description: Warracker is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/sassanix/Warracker/blob/main/CHANGELOG.md
date_added: '2025-04-21'
description: Warracker is an open-source web application to manage product warranties,
  track expiration dates, and store related documents.
home: https://github.com/sassanix/Warracker
host_mounts: []
icon: https://media.sys.truenas.net/apps/warracker/icons/icon.png
keywords:
- warranty
- expiration
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: warracker
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [warracker] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/warracker/screenshots/screenshot1.png
sources:
- https://github.com/sassanix/Warracker
title: Warracker
train: community
version: 1.2.1
