annotations:
  min_scale_version: 24.10.2.2
app_version: v1.5.857
capabilities: []
categories:
- productivity
changelog_url: https://github.com/mumble-voip/mumble/releases
date_added: '2024-08-02'
description: Mumble is a free, open source, low latency, high quality voice chat application.
home: https://www.mumble.info/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mumble/icons/icon.svg
keywords:
- voice
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mumble
run_as_context:
- description: Container [mumble] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/mumble-voip/mumble-docker
- https://www.mumble.info/
title: Mumble
train: community
version: 1.4.2
