app_version: 0.66.0
capabilities:
- description: NetBird Client is able to perform network administration tasks
  name: NET_ADMIN
- description: NetBird Client is able to use raw and packet sockets
  name: NET_RAW
- description: NetBird Client is able to perform system administration operations
  name: SYS_ADMIN
- description: NetBird Client is able to override resource limits
  name: SYS_RESOURCE
categories:
- networking
changelog_url: https://github.com/netbirdio/netbird/releases
date_added: '2026-01-27'
description: "Connect your devices into a secure WireGuard\xAE-based overlay network\
  \ with SSO, MFA and granular access controls."
home: https://netbird.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/netbird-client/icons/icon.svg
keywords:
- vpn
- netbird
- wireguard
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: netbird-client
run_as_context:
- description: Container [netbird-client] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://netbird.io/
title: NetBird Client
train: community
version: 1.1.5
