annotations:
  min_scale_version: 24.10.2.2
app_version: 2.13.3
capabilities: []
categories:
- productivity
changelog_url: https://github.com/penpot/penpot/blob/main/CHANGES.md
date_added: '2024-10-25'
description: Penpot - The open-source design tool for design and code collaboration
home: https://penpot.app/
host_mounts: []
icon: https://media.sys.truenas.net/apps/penpot/icons/icon.svg
keywords:
- design
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: penpot
run_as_context:
- description: Container [penpot-backend] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [penpot-exporter] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [penpot-frontend] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot1.webp
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot2.webp
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot3.webp
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot4.webp
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot5.webp
- https://media.sys.truenas.net/apps/penpot/screenshots/screenshot6.webp
sources:
- https://github.com/penpot/penpot
title: Penpot
train: community
version: 1.4.0
