app_version: 1.16.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/Spottarr/Spottarr/releases
date_added: '2025-04-25'
description: Spottarr is a small application that can index the spotnet messages (spots)
  and exposes them as a newznab indexer.
home: https://github.com/Spottarr/Spottarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/spottarr/icons/icon.svg
keywords:
- media
- newsserver
- download
- newznab
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: spottarr
run_as_context:
- description: Container [spottarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
sources:
- https://github.com/Spottarr/Spottarr
title: Spottarr
train: community
version: 1.1.2
