app_version: debian
capabilities:
- description: Steam Headless is able to write records to audit log
  name: AUDIT_WRITE
- description: Steam Headless is able to change file ownership arbitrarily
  name: CHOWN
- description: Steam Headless is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Steam Headless is able to bypass permission checks for file operations
  name: FOWNER
- description: Steam Headless is able to preserve set-user-ID and set-group-ID bits
  name: FSETID
- description: Steam Headless is able to send signals to any process
  name: KILL
- description: Steam Headless is able to create special files using mknod()
  name: MKNOD
- description: Steam Headless is able to perform network administration tasks
  name: NET_ADMIN
- description: Steam Headless is able to change group ID of processes
  name: SETGID
- description: Steam Headless is able to change user ID of processes
  name: SETUID
- description: Steam Headless is able to perform system administration operations
  name: SYS_ADMIN
- description: Steam Headless is able to modify process scheduling priority
  name: SYS_NICE
- description: Steam Headless is able to override resource limits
  name: SYS_RESOURCE
categories:
- games
date_added: '2025-01-22'
description: A Headless Steam Docker image supporting NVIDIA GPU and accessible via
  Web UI
home: https://github.com/Steam-Headless/docker-steam-headless
host_mounts:
- description: DBus Socket
  host_path: /var/run/dbus
- description: Fuse Device
  host_path: /dev/fuse
- description: UInput Device
  host_path: /dev/uinput
icon: https://media.sys.truenas.net/apps/steam-headless/icons/icon.png
keywords:
- games
- steam
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: steam-headless
run_as_context:
- description: Container [steam-headless] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/Steam-Headless/docker-steam-headless
title: Steam Headless
train: community
version: 1.1.2
