app_version: 1.85.0
capabilities: []
categories:
- networking
changelog_url: https://www.twingate.com/changelog
date_added: '2026-02-03'
description: Identity-based access for users, services, and AI agents that deploys
  in minutes, scales to every resource, and finally lets you retire your VPN.
home: https://www.twingate.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/twingate-connector/icons/icon.svg
keywords:
- vpn
- twingate
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: twingate-connector
run_as_context:
- description: Container [twingate-connector] runs as non-root user and group.
  gid: 65532
  group_name: Host group is [unknown (65532)]
  uid: 65532
  user_name: Host user is [unknown (65532)]
screenshots: []
sources:
- https://www.twingate.com/
title: Twingate Connector
train: community
version: 1.1.2
