app_version: latest
capabilities: []
categories:
- media
date_added: '2025-10-03'
description: An alternative privacy-friendly YouTube frontend which is efficient by
  design.
home: https://github.com/TeamPiped/Piped
host_mounts: []
icon: https://media.sys.truenas.net/apps/piped/icons/icon.svg
keywords:
- youtube
- frontend
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: piped
run_as_context:
- description: Container [backend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [bg_helper] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [frontend] runs as non-root user and group.
  gid: 101
  group_name: Host group is [systemd-timesync]
  uid: 101
  user_name: Host user is [systemd-timesync]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [proxy] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://docs.piped.video
- https://github.com/TeamPiped/Piped
title: Piped
train: community
version: 1.2.0
