annotations:
  min_scale_version: 24.10.2.2
app_version: RELEASE.2025-09-07T16-13-09Z
capabilities: []
categories:
- storage
changelog_url: https://github.com/minio/minio/tags
date_added: '2024-07-31'
description: The Object Store for AI Data Infrastructure
home: https://min.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
keywords:
- storage
- object-storage
- S3
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: minio
run_as_context:
- description: Container [minio] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot3.png
sources:
- https://github.com/minio/minio
title: MinIO
train: stable
version: 1.4.2
