app_version: 2.8.0
capabilities: []
categories:
- database
changelog_url: https://docs.influxdata.com/influxdb/v2/reference/release-notes/influxdb/
date_added: '2025-01-31'
description: Scalable datastore for metrics, events, and real-time analytics
home: https://influxdata.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/influxdb/icons/icon.png
keywords:
- metrics
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: influxdb
run_as_context:
- description: Container [influxdb] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/influxdata/influxdb
- https://github.com/influxdata/influxdata-docker
title: InfluxDB
train: community
version: 1.2.1
