app_version: v1.29.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/axllent/mailpit/releases
date_added: '2026-01-21'
description: An email and SMTP testing tool with API for developers
home: https://mailpit.axllent.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mailpit/icons/icon.svg
keywords:
- email
- smtp
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mailpit
run_as_context:
- description: Container [mailpit] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/axllent/mailpit
title: Mailpit
train: community
version: 1.1.3
