annotations:
  min_scale_version: 24.10.2.2
app_version: 2.0.22
capabilities: []
categories:
- networking
changelog_url: https://github.com/eclipse-mosquitto/mosquitto/blob/master/ChangeLog.txt
date_added: '2024-11-15'
description: Eclipse Mosquitto is an open source MQTT broker
home: https://mosquitto.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/eclipse-mosquitto/icons/icon.svg
keywords:
- networking
- mqtt
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: eclipse-mosquitto
run_as_context:
- description: Container [mosquitto] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/eclipse-mosquitto/mosquitto
- https://hub.docker.com/_/eclipse-mosquitto
title: Eclipse Mosquitto
train: community
version: 1.2.0
