annotations:
  min_scale_version: 24.10.2.2
app_version: 2.2.0
capabilities:
- description: Deluge is able to change file ownership arbitrarily
  name: CHOWN
- description: Deluge is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Deluge is able to bypass permission checks for file operations
  name: FOWNER
- description: Deluge is able to change group ID of processes
  name: SETGID
- description: Deluge is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://git.deluge-torrent.org/deluge/log/
date_added: '2024-08-02'
description: Deluge is a lightweight, Free Software, cross-platform BitTorrent client.
home: https://deluge-torrent.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/deluge/icons/icon.png
keywords:
- torrent
- download
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: deluge
run_as_context:
- description: Container [deluge] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/linuxserver/docker-deluge
- https://deluge-torrent.org/
title: Deluge
train: community
version: 1.3.2
