app_version: 2025.12.4
capabilities: []
categories:
- authentication
changelog_url: https://docs.goauthentik.io/docs/releases/
date_added: '2025-03-25'
description: The authentication glue you need.
home: https://goauthentik.io/
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/authentik/icons/icon.svg
keywords:
- authentik
- auth
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: authentik
run_as_context:
- description: Container [authentik-server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [authentik-worker] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/authentik/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/authentik/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/authentik/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/authentik/screenshots/screenshot4.png
sources:
- https://goauthentik.io/
- https://github.com/goauthentik/authentik
title: Authentik
train: community
version: 1.2.1
