app_version: v3.13.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/woodpecker-ci/woodpecker/releases
date_added: '2025-05-21'
description: Woodpecker CI is a simple, yet powerful CI/CD engine with great extensibility.
home: https://woodpecker-ci.org
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/woodpecker-ci/icons/icon.svg
keywords:
- automation
- ci
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: woodpecker-ci
run_as_context:
- description: Container [agent] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://woodpecker-ci.org
- https://github.com/woodpecker-ci/woodpecker
- https://hub.docker.com/r/woodpeckerci/woodpecker-server
- https://hub.docker.com/r/woodpeckerci/woodpecker-agent
title: Woodpecker CI
train: community
version: 1.1.2
