app_version: latest
capabilities:
- description: TrueNAS WebUI is able to change file ownership arbitrarily
  name: CHOWN
- description: TrueNAS WebUI is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: TrueNAS WebUI is able to bypass permission checks for file operations
  name: FOWNER
- description: TrueNAS WebUI is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: TrueNAS WebUI is able to change group ID of processes
  name: SETGID
- description: TrueNAS WebUI is able to change user ID of processes
  name: SETUID
categories:
- development
date_added: '2025-01-22'
description: TrueNAS WebUI DEVELOPMENT ONLY
home: https://www.truenas.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-app/icons/icon.webp
keywords: []
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: truenas-webui
run_as_context:
- description: Container [truenas-webui] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/truenas/webui
title: TrueNAS WebUI
train: dev
version: 1.1.2
