app_version: v26.02.1
capabilities:
- description: MKVToolNix is able to change file ownership arbitrarily
  name: CHOWN
- description: MKVToolNix is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: MKVToolNix is able to bypass permission checks for file operations
  name: FOWNER
- description: MKVToolNix is able to send signals to any process
  name: KILL
- description: MKVToolNix is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: MKVToolNix is able to change group ID of processes
  name: SETGID
- description: MKVToolNix is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/jlesage/docker-mkvtoolnix/releases
date_added: '2025-12-11'
description: MKVToolNix is a set of tools to create, alter and inspect Matroska files.
home: https://mkvtoolnix.download/docs.html
host_mounts: []
icon: https://media.sys.truenas.net/apps/mkvtoolnix/icons/icon.png
keywords:
- media
- video
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mkvtoolnix
run_as_context:
- description: Container [mkvtoolnix] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/jlesage/docker-mkvtoolnix
title: MKVToolNix
train: community
version: 1.1.2
