annotations:
  min_scale_version: 24.10.2.2
app_version: 2.3.1
capabilities:
- description: Flame is able to change file ownership arbitrarily
  name: CHOWN
- description: Flame is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Flame is able to bypass permission checks for file operations
  name: FOWNER
categories:
- productivity
changelog_url: https://github.com/pawelmalak/flame/blob/master/CHANGELOG.md
date_added: '2024-08-01'
description: Flame is a self-hosted start page for your server.
home: https://github.com/pawelmalak/flame
host_mounts: []
icon: https://media.sys.truenas.net/apps/flame/icons/icon.png
keywords:
- startpage
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: flame
run_as_context:
- description: Container [flame] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/flame/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/pawelmalak/flame
- https://github.com/pawelmalak/flame
title: Flame
train: community
version: 1.3.1
