app_version: 0.8.1
capabilities: []
categories:
- media
changelog_url: https://github.com/TheNickOfTime/handbrake-web/releases
date_added: '2025-01-15'
description: A self-hosted platform to use HandBrake on your headless devices via
  a bespoke web interface. Harness the processing power of multiple devices to work
  on a single queue.
home: https://github.com/TheNickOfTime/handbrake-web
host_mounts: []
icon: https://media.sys.truenas.net/apps/handbrake-web/icons/icon.png
keywords:
- media
- video
- transcoder
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: handbrake-web
run_as_context:
- description: Container [handbrake-server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [handbrake-worker] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/handbrake-web/screenshots/screenshot6.png
sources:
- https://github.com/TheNickOfTime/handbrake-web
title: Handbrake Web
train: community
version: 1.2.0
