app_version: 12.2.1
capabilities:
- description: mitmproxy is able to change file ownership arbitrarily
  name: CHOWN
- description: mitmproxy is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: mitmproxy is able to bypass permission checks for file operations
  name: FOWNER
- description: mitmproxy is able to change group ID of processes
  name: SETGID
- description: mitmproxy is able to change user ID of processes
  name: SETUID
categories:
- networking
changelog_url: https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md
date_added: '2025-03-24'
description: mitmproxy is your swiss-army knife for debugging, testing, privacy measurements,
  and penetration testing.
home: https://mitmproxy.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/mitmproxy/icons/icon.svg
keywords:
- mitmproxy
- network
- proxy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mitmproxy
run_as_context:
- description: Container [mitmproxy] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/mitmproxy/mitmproxy
title: mitmproxy
train: community
version: 1.1.1
