app_version: v1.54.0
capabilities:
- description: Homarr is able to change file ownership arbitrarily
  name: CHOWN
- description: Homarr is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Homarr is able to bypass permission checks for file operations
  name: FOWNER
- description: Homarr is able to change group ID of processes
  name: SETGID
- description: Homarr is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/homarr-labs/homarr/releases
date_added: '2024-08-02'
description: Homarr a modern and easy to use dashboard. 14+ integrations. 10K+ icons
  built in. Authentication out of the box. No YAML, drag and drop configuration.
home: https://homarr.dev/
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/homarr/icons/icon.svg
keywords:
- dashboard
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: homarr
run_as_context:
- description: Container [homarr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/homarr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/homarr/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/homarr/screenshots/screenshot3.png
sources:
- https://homarr.dev/
- https://github.com/homarr-labs/homarr
title: Homarr
train: community
version: 2.2.4
