annotations:
  min_scale_version: 24.10.2.2
app_version: 2026.2.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES
date_added: '2024-08-02'
description: Cloudflared is a client for Cloudflare Tunnel, a daemon that exposes
  private services through the Cloudflare edge.
home: https://github.com/cloudflare/cloudflared
host_mounts: []
icon: https://media.sys.truenas.net/apps/cloudflared/icons/icon.svg
keywords:
- network
- cloudflare
- tunnel
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cloudflared
run_as_context:
- description: Container [cloudflared] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/cloudflare/cloudflared
- https://hub.docker.com/r/cloudflare/cloudflared
title: Cloudflared
train: community
version: 1.4.0
