app_version: 0.26.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/usememos/memos/releases
date_added: '2025-12-15'
description: An open-source, self-hosted note-taking service. Your thoughts, your
  data, your control - no tracking, no ads, no subscription fees.
home: https://usememos.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/memos/icons/icon.png
keywords:
- note-taking
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: memos
run_as_context:
- description: Container [memos] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/usememos/memos
title: Memos
train: community
version: 1.1.0
