annotations:
  min_scale_version: 24.10.2.2
app_version: 6.9.1
capabilities:
- description: WordPress is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- productivity
changelog_url: https://wordpress.org/news/category/releases/
date_added: '2024-09-20'
description: WordPress is a web content management system
home: https://wordpress.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/wordpress/icons/icon.png
keywords:
- cms
- blog
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: wordpress
run_as_context:
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [wordpress] runs as non-root user and group.
  gid: 33
  group_name: Host group is [www-data]
  uid: 33
  user_name: Host user is [www-data]
screenshots:
- https://media.sys.truenas.net/apps/wordpress/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/wordpress/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/wordpress/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/wordpress/screenshots/screenshot4.png
sources:
- https://hub.docker.com/_/wordpress
title: WordPress
train: community
version: 1.3.1
