app_version: 2.7.6
capabilities:
- description: Cleanuparr is able to change file ownership arbitrarily
  name: CHOWN
- description: Cleanuparr is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Cleanuparr is able to bypass permission checks for file operations
  name: FOWNER
- description: Cleanuparr is able to change group ID of processes
  name: SETGID
- description: Cleanuparr is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/Cleanuparr/Cleanuparr/releases
date_added: '2025-09-25'
description: Cleanuparr is a tool for automating the cleanup of unwanted or blocked
  files in Sonarr, Radarr, and supported download clients like qBittorrent, Deluge
  and Transmission.
home: https://github.com/Cleanuparr/Cleanuparr
host_mounts: []
icon: https://media.sys.truenas.net/apps/cleanuparr/icons/icon.svg
keywords:
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cleanuparr
run_as_context:
- description: Container [cleanuparr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/Cleanuparr/Cleanuparr
title: Cleanuparr
train: community
version: 1.1.8
