app_version: v29.3
capabilities: []
categories:
- financial
date_added: '2025-08-11'
description: Run your personal node powered by Bitcoin Knots.
home: https://bitcoinknots.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitcoind-knots/icons/icon.png
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bitcoind-knots
run_as_context:
- description: Container [bitcoind] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://bitcoinknots.org
- https://github.com/Retropex/docker-bitcoind-truenas
title: Bitcoin Knots
train: community
version: 1.1.2
