annotations:
  min_scale_version: 24.10.2.2
app_version: 5.1.4
capabilities: []
categories:
- media
changelog_url: https://www.qbittorrent.org/news
date_added: '2024-07-30'
description: The qBittorrent project aims to provide an open-source software alternative
  to mTorrent.
home: https://www.qbittorrent.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/qbittorrent/icons/icon.png
keywords:
- media
- torrent
- download
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: qbittorrent
run_as_context:
- description: Container [qbittorrent] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/qbittorrent/screenshots/screenshot1.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/qbittorrent
- https://www.qbittorrent.org/
title: qBittorrent
train: community
version: 1.4.1
