app_version: 4.9.0
capabilities: []
categories:
- games
changelog_url: https://gitlab.com/crafty-controller/crafty-4/-/releases
date_added: '2025-04-04'
description: Crafty 4 is the next iteration of our Minecraft Server Wrapper/Controller/Launcher
home: https://craftycontrol.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/crafty-4/icons/icon.png
keywords:
- minecraft
- crafty
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: crafty-4
run_as_context:
- description: Container [crafty-4] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://gitlab.com/crafty-controller/crafty-4
title: Crafty 4
train: community
version: 1.1.1
