app_version: 2.26.1
capabilities: []
categories:
- media
changelog_url: https://github.com/maintainerr/Maintainerr/releases
date_added: '2025-05-27'
description: Maintainerr is a media collection maintenance tool for the Plex ecosystem.
home: https://maintainerr.info/
host_mounts: []
icon: https://media.sys.truenas.net/apps/maintainerr/icons/icon.svg
keywords:
- media
- plex
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: maintainerr
run_as_context:
- description: Container [maintainerr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/maintainerr/Maintainerr
title: Maintainerr
train: community
version: 1.1.1
