app_version: latest
capabilities:
- description: LanCache Monolithic is able to change file ownership arbitrarily
  name: CHOWN
- description: LanCache Monolithic is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: LanCache Monolithic is able to bypass permission checks for file operations
  name: FOWNER
- description: LanCache Monolithic is able to change group ID of processes
  name: SETGID
- description: LanCache Monolithic is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: ''
date_added: '2025-05-22'
description: LanCache Monolithic is a monolithic lancache service capable of caching
  all CDNs in a single instance
home: https://lancache.net/
host_mounts: []
icon: https://media.sys.truenas.net/apps/lancache-monolithic/icons/icon.svg
keywords:
- lancache
- games
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: lancache-monolithic
run_as_context:
- description: Container [lancache-monolithic] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/lancachenet/monolithic
- https://lancache.net/docs/containers/monolithic/
- https://github.com/lancachenet/monolithic
title: LanCache Monolithic
train: community
version: 1.1.2
