annotations:
  min_scale_version: 24.10.2.2
app_version: amd64-3.5.2
capabilities: []
categories:
- productivity
changelog_url: https://joplinapp.org/help/about/changelog/server
date_added: '2024-08-13'
description: Joplin is an open source note-taking app. Capture your thoughts and securely
  access them from any device
home: https://joplinapp.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/joplin/icons/icon.png
keywords:
- notes
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: joplin
run_as_context:
- description: Container [joplin] runs as non-root user and group.
  gid: 1001
  group_name: Host group is [unknown (1001)]
  uid: 1001
  user_name: Host user is [unknown (1001)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/joplin/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/joplin/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/joplin/screenshots/screenshot3.png
sources:
- https://github.com/laurent22/joplin
- https://hub.docker.com/r/joplin/server/
title: Joplin
train: community
version: 1.5.2
