app_version: 2.0.0
capabilities: []
categories:
- networking
changelog_url: https://gitlab.torproject.org/tpo/core/arti/-/blob/main/CHANGELOG.md
date_added: '2025-02-25'
description: Arti is an experimental Tor implementation written in Rust, and it is
  designed to be modular, reusable, and easy to audit.
home: https://tpo.pages.torproject.net/core/arti/
host_mounts: []
icon: https://media.sys.truenas.net/apps/arti/icons/icon.png
keywords:
- tor
- privacy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: arti
run_as_context:
- description: Container [arti] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://tpo.pages.torproject.net/core/arti/
- https://github.com/MAGICGrants/arti-docker
title: Arti
train: community
version: 1.3.2
