app_version: v10.0.4
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/amir20/dozzle/releases
date_added: '2025-01-31'
description: Realtime log viewer for docker containers.
home: https://dozzle.dev
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/dozzle/icons/icon.svg
keywords:
- logs
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dozzle
run_as_context:
- description: Container [dozzle] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/amir20/dozzle
title: Dozzle
train: community
version: 1.1.4
