app_version: 8.2.5
capabilities: []
categories:
- database
changelog_url: https://www.mongodb.com/docs/manual/release-notes/
date_added: '2025-05-12'
description: MongoDB is a document database designed for ease of application development
  and scaling.
home: https://www.mongodb.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mongodb/icons/icon.svg
keywords:
- database
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mongodb
run_as_context:
- description: Container [mongodb] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/_/mongo
title: MongoDB
train: community
version: 1.1.0
