app_version: v3.2.1
capabilities: []
categories:
- financial
changelog_url: https://github.com/mempool/mempool/releases
date_added: '2025-04-25'
description: A fully-featured Bitcoin mempool visualizer, block explorer, and API
  service.
home: https://mempool.space
host_mounts: []
icon: https://media.sys.truenas.net/apps/mempool/icons/icon.svg
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mempool
run_as_context:
- description: Container [backend] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [frontend] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/mempool/mempool
title: Mempool
train: community
version: 1.1.1
