app_version: 8.0.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/concourse/concourse/releases
date_added: '2025-05-02'
description: Concourse is a container-based automation system written in Go.
home: https://concourse-ci.org
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/concourse/icons/icon.svg
keywords:
- automation
- ci
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: concourse
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [web] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [worker] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://concourse-ci.org
- https://github.com/concourse/concourse
- https://hub.docker.com/r/concourse/concourse
title: Concourse
train: community
version: 1.2.2
