annotations:
  min_scale_version: 24.10.2.2
app_version: 2.0.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/plankanban/planka/releases
date_added: '2024-09-10'
description: Planka is an Elegant open source project tracking
home: https://github.com/plankanban/planka
host_mounts: []
icon: https://media.sys.truenas.net/apps/planka/icons/icon.png
keywords:
- kanban
- project
- task
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: planka
run_as_context:
- description: Container [planka] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/planka/screenshots/screenshot1.png
sources:
- https://github.com/plankanban/planka
title: Planka
train: community
version: 2.2.0
