annotations:
  min_scale_version: 24.10.2.2
app_version: 1.0.2
capabilities:
- description: Rsyncd is able to change file ownership arbitrarily
  name: CHOWN
- description: Rsyncd is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Rsyncd is able to bypass permission checks for file operations
  name: FOWNER
- description: Rsyncd is able to set file capabilities on other files
  name: SETFCAP
- description: Rsyncd is able to change group ID of processes
  name: SETGID
- description: Rsyncd is able to change user ID of processes
  name: SETUID
- description: Rsyncd is able to use chroot() system call
  name: SYS_CHROOT
categories:
- storage
date_added: '2024-08-28'
description: Rsync is an open source utility that provides fast incremental file transfer.
home: https://github.com/truenas/containers/tree/master/apps/rsyncd
host_mounts: []
icon: https://media.sys.truenas.net/apps/rsyncd/icons/icon.png
keywords:
- sync
- rsync
- file transfer
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rsyncd
run_as_context:
- description: Container [rsyncd] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/truenas/containers/tree/master/apps/rsyncd
- https://hub.docker.com/r/ixsystems/rsyncd
title: Rsync Daemon
train: community
version: 1.3.1
