annotations:
  min_scale_version: 24.10.2.2
app_version: v1.2.0
capabilities: []
categories:
- media
changelog_url: https://github.com/Casvt/Kapowarr/releases
date_added: '2024-08-09'
description: Kapowarr is a software to build and manage a comic book library, fitting
  in the *arr suite of software.
home: https://casvt.github.io/Kapowarr/
host_mounts: []
icon: https://media.sys.truenas.net/apps/kapowarr/icons/icon.svg
keywords:
- comic
- media
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kapowarr
run_as_context:
- description: Container [kapowarr] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/kapowarr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/kapowarr/screenshots/screenshot2.png
sources:
- https://hub.docker.com/r/mrcas/kapowarr
- https://github.com/Casvt/Kapowarr
title: Kapowarr
train: community
version: 1.3.1
