annotations:
  min_scale_version: 24.10.2.2
app_version: 6.1.0.19
capabilities:
- description: Omada Controller is able to change file ownership arbitrarily
  name: CHOWN
- description: Omada Controller is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Omada Controller is able to bypass permission checks for file operations
  name: FOWNER
- description: Omada Controller is able to change group ID of processes
  name: SETGID
- description: Omada Controller is able to change user ID of processes
  name: SETUID
categories:
- networking
changelog_url: https://github.com/mbentley/docker-omada-controller/releases
date_added: '2024-08-02'
description: Omada Controller (TP-Link) is a network management controller for TP-Link
  Omada Equipment
home: https://github.com/mbentley/docker-omada-controller
host_mounts: []
icon: https://media.sys.truenas.net/apps/omada-controller/icons/icon.svg
keywords:
- network
- controller
- omada
- tp-link
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: omada-controller
run_as_context:
- description: Container [omada] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/mbentley/docker-omada-controller
- https://hub.docker.com/r/mbentley/omada-controller
title: Omada Controller
train: community
version: 1.4.1
