app_version: 11.11.0
capabilities: []
categories:
- home-automation
changelog_url: https://github.com/zwave-js/zwave-js-ui/releases
date_added: '2025-06-13'
description: Full featured Z-Wave Control Panel UI and MQTT gateway. Built using Nodejs,
  and Vue/Vuetify
home: https://zwave-js.github.io/zwave-js-ui
host_mounts: []
icon: https://media.sys.truenas.net/apps/zwave-js-ui/icons/icon.svg
keywords:
- zwave
- mqtt
- bridge
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zwave-js-ui
run_as_context:
- description: Container [zwave] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/zwave-js/zwave-js-ui
title: Z-Wave JS UI
train: community
version: 1.1.0
