app_version: v0.9.2
capabilities: []
categories:
- productivity
changelog_url: https://github.com/Notifiarr/notifiarr/releases
date_added: '2025-05-20'
description: Client for Notifiarr.com
home: https://notifiarr.com/
host_mounts:
- description: UTMP
  host_path: /var/run/utmp
icon: https://media.sys.truenas.net/apps/notifiarr/icons/icon.png
keywords:
- notifiarr
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: notifiarr
run_as_context:
- description: Container [notifiarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Notifiarr/notifiarr
title: Notifiarr
train: community
version: 1.1.2
