annotations:
  min_scale_version: 24.10.2.2
app_version: v3.11.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/mealie-recipes/mealie/releases
date_added: '2024-08-22'
description: Mealie is a self-hosted recipe manager and meal planner
home: https://docs.mealie.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mealie/icons/icon.png
keywords:
- recipes
- meal planner
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: mealie
run_as_context:
- description: Container [mealie] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/mealie/screenshots/screenshot1.png
sources:
- https://docs.mealie.io/
title: Mealie
train: community
version: 1.7.2
