app_version: 0.18.4
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/henrygd/beszel/releases
date_added: '2026-01-22'
description: Lightweight server monitoring hub with historical data, docker stats,
  and alerts.
home: https://www.beszel.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/beszel-hub/icons/icon.svg
keywords:
- monitoring
- alerts
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: beszel-hub
run_as_context:
- description: Container [beszel] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/henrygd/beszel
title: Beszel Hub
train: community
version: 1.1.3
