app_version: v2.17.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/binwiederhier/ntfy/releases
date_added: '2025-05-29'
description: ntfy (pronounced "notify") is a simple HTTP-based pub-sub notification
  service.
home: https://ntfy.sh/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ntfy/icons/icon.svg
keywords:
- notification
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ntfy
run_as_context:
- description: Container [ntfy] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/binwiederhier/ntfy
- https://hub.docker.com/r/binwiederhier/ntfy
title: ntfy
train: community
version: 1.1.1
