app_version: v0.17.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/C4illin/ConvertX/releases
date_added: '2025-05-05'
description: ConvertX is a self-hosted online file converter with support for over
  1000 formats
home: https://github.com/C4illin/ConvertX
host_mounts: []
icon: https://media.sys.truenas.net/apps/convertx/icons/icon.png
keywords:
- convertx
- files
- conversion
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: convertx
run_as_context:
- description: Container [convertx] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/C4illin/ConvertX
title: ConvertX
train: community
version: 1.1.1
