annotations:
  min_scale_version: 24.10.2.2
app_version: 2026.02.27
capabilities: []
categories:
- media
date_added: '2024-08-02'
description: MeTube is a web GUI for youtube-dl (using the yt-dlp fork) with playlist
  support.
home: https://github.com/alexta69/metube
host_mounts: []
icon: https://media.sys.truenas.net/apps/metube/icons/icon.svg
keywords:
- youtube-dl
- yt-dlp
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: metube
run_as_context:
- description: Container [metube] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/metube/screenshots/screenshot1.png
sources:
- https://github.com/alexta69/metube
title: MeTube
train: community
version: 1.4.5
