app_version: 2.1.2
capabilities: []
categories:
- media
changelog_url: https://github.com/jaymoulin/docker-jdownloader/releases
date_added: '2025-03-19'
description: JDownloader is a free, open-source download management tool with a huge
  community that makes downloading as easy and fast as it should be.
home: https://github.com/jaymoulin/docker-jdownloader
host_mounts: []
icon: https://media.sys.truenas.net/apps/jdownloader2/icons/icon.png
keywords:
- media
- download
- files
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: jdownloader2
run_as_context:
- description: Container [jdownloader2] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/jaymoulin/docker-jdownloader
title: JDownloader2
train: community
version: 1.1.1
