app_version: 2.3.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/alam00000/bentopdf/releases
date_added: '2025-11-04'
description: A Privacy First PDF Toolkit
home: https://bentopdf.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bentopdf/icons/icon.svg
keywords:
- pdf
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bentopdf
run_as_context:
- description: Container [bentopdf] runs as non-root user and group.
  gid: 101
  group_name: Host group is [systemd-timesync]
  uid: 101
  user_name: Host user is [systemd-timesync]
screenshots: []
sources:
- https://github.com/alam00000/bentopdf
title: BentoPDF
train: community
version: 1.1.3
