app_version: v4.10.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/chatwoot/chatwoot/releases
date_added: '2025-06-24'
description: Open-source live-chat, email support, omni-channel desk. An alternative
  to Intercom, Zendesk, Salesforce Service Cloud etc.
home: https://www.chatwoot.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/chatwoot/icons/icon.svg
keywords:
- support
- live chat
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: chatwoot
run_as_context:
- description: Container [chatwoot] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [sidekiq] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/chatwoot/chatwoot
- https://hub.docker.com/r/chatwoot/chatwoot
title: Chatwoot
train: community
version: 1.1.0
