annotations:
  min_scale_version: 24.10.2.2
app_version: 9.3.0
capabilities:
- description: Calibre is able to change file ownership arbitrarily
  name: CHOWN
- description: Calibre is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Calibre is able to bypass permission checks for file operations
  name: FOWNER
- description: Calibre is able to change group ID of processes
  name: SETGID
- description: Calibre is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://calibre-ebook.com/whats-new
date_added: '2024-11-19'
description: Calibre is the one stop solution for all your e-book needs.
home: https://calibre-ebook.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/calibre/icons/icon.png
keywords:
- media
- ebooks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: calibre
run_as_context:
- description: Container [calibre] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/calibre/screenshots/screenshot6.png
sources:
- https://github.com/linuxserver/docker-calibre
- https://github.com/kovidgoyal/calibre
- https://calibre-ebook.com/
title: Calibre
train: community
version: 1.2.3
