app_version: v5.34.0
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/TwiN/gatus/releases
date_added: '2025-11-03'
description: Automated developer-oriented status page
home: https://gatus.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/gatus/icons/icon.svg
keywords:
- monitoring
- status page
- uptime
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gatus
run_as_context:
- description: Container [gatus] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/TwiN/gatus
title: Gatus
train: community
version: 1.1.2
