app_version: 2024.10.22-7ca5933
capabilities:
- description: IT Tools is able to change file ownership arbitrarily
  name: CHOWN
- description: IT Tools is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: IT Tools is able to bypass permission checks for file operations
  name: FOWNER
- description: IT Tools is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
- description: IT Tools is able to change group ID of processes
  name: SETGID
- description: IT Tools is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/CorentinTh/it-tools/blob/main/CHANGELOG.md
date_added: '2025-01-24'
description: Collection of handy online tools for developers, with great UX.
home: https://it-tools.tech
host_mounts: []
icon: https://media.sys.truenas.net/apps/it-tools/icons/icon.svg
keywords:
- tools
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: it-tools
run_as_context:
- description: Container [it-tools] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/CorentinTh/it-tools/
title: IT Tools
train: community
version: 1.1.1
