app_version: 1.20.7
capabilities: []
categories:
- storage
changelog_url: https://github.com/9001/copyparty/releases
date_added: '2025-10-02'
description: Portable file server with accelerated resumable uploads, dedup, WebDAV,
  FTP, TFTP, zeroconf, media indexer, thumbnails++ all in one file, no deps
home: https://github.com/9001/copyparty
host_mounts: []
icon: https://media.sys.truenas.net/apps/copyparty/icons/icon.svg
keywords:
- file-server
- ftp
- webdav
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: copyparty
run_as_context:
- description: Container [copyparty] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
sources:
- https://github.com/9001/copyparty
title: Copyparty
train: community
version: 1.1.0
