app_version: 0.53.3
capabilities: []
categories:
- productivity
changelog_url: https://github.com/dgtlmoon/changedetection.io/releases/
date_added: '2025-05-09'
description: Page change monitoring with alerts a breeze. The best way to monitor
  website changes.
home: https://changedetection.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/change-detection/icons/icon.svg
keywords:
- change-detection
- page monitoring
- price tracker
- stock tracker
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: change-detection
run_as_context:
- description: Container [change-detection] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/change-detection/screenshots/screenshot1.png
sources:
- https://github.com/dgtlmoon/changedetection.io
title: ChangeDetection.io
train: community
version: 1.1.1
