app_version: i2p-2.10.0-5
capabilities: []
categories:
- networking
changelog_url: https://geti2p.net/en/blog/
date_added: '2025-02-26'
description: I2P (Invisible Internet Protocol) is a universal anonymous network layer.
  All communications over I2P are anonymous and end-to-end encrypted, participants
  don't reveal their real IP addresses.
home: https://geti2p.net
host_mounts: []
icon: https://media.sys.truenas.net/apps/i2p/icons/icon.png
keywords:
- i2p
- privacy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: i2p
run_as_context:
- description: Container [i2p] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://geti2p.net
- https://github.com/i2p/i2p.i2p
title: I2P
train: community
version: 1.1.1
