app_version: 1.6.40
capabilities: []
categories:
- database
changelog_url: https://github.com/memcached/memcached/wiki/ReleaseNotes
date_added: '2025-06-24'
description: Memcached is a high-performance, distributed memory object caching system.
home: https://memcached.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/memcached/icons/icon.png
keywords:
- database
- cache
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: memcached
run_as_context:
- description: Container [memcached] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://hub.docker.com/_/memcached
- https://github.com/memcached/memcached
title: Memcached
train: community
version: 1.1.0
