app_version: 2.5.3
capabilities:
- description: Recipes is able to change file ownership arbitrarily
  name: CHOWN
- description: Recipes is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Recipes is able to bypass permission checks for file operations
  name: FOWNER
- description: Recipes is able to change group ID of processes
  name: SETGID
- description: Recipes is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/TandoorRecipes/recipes/releases
date_added: '2025-11-06'
description: Tandoor Recipes is an application for managing recipes, planning meals,
  building shopping lists and much much more!
home: https://tandoor.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/tandoor-recipes/icons/icon.svg
keywords:
- recipes
- meal planning
- cooking
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: tandoor-recipes
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [recipes] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/TandoorRecipes/recipes
- https://docs.tandoor.dev/
title: Tandoor Recipes
train: community
version: 1.1.2
