annotations:
  min_scale_version: 24.10.2.2
app_version: 1.28.1
capabilities:
- description: FreshRSS is able to change file ownership arbitrarily
  name: CHOWN
- description: FreshRSS is able to change group ID of processes
  name: SETGID
- description: FreshRSS is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/FreshRSS/FreshRSS/blob/edge/CHANGELOG.md
date_added: '2024-08-09'
description: FreshRSS is a free, self-hostable news aggregator
home: https://freshrss.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/freshrss/icons/icon.png
keywords:
- rss
- news
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: freshrss
run_as_context:
- description: Container [fresh_rss] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/freshrss/screenshots/screenshot1.webp
sources:
- https://github.com/FreshRSS/FreshRSS
- https://hub.docker.com/r/freshrss/freshrss
title: FreshRSS
train: community
version: 1.6.2
