annotations:
  min_scale_version: 24.10.2.2
app_version: 1.5.5
capabilities: []
categories:
- media
changelog_url: https://github.com/morpheus65535/bazarr/releases
date_added: '2024-07-31'
description: Bazarr is a companion application to Sonarr and Radarr. It manages and
  downloads subtitles based on your requirements.
home: https://www.bazarr.media
host_mounts: []
icon: https://media.sys.truenas.net/apps/bazarr/icons/icon.png
keywords:
- media
- subtitles
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bazarr
run_as_context:
- description: Container [bazarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/bazarr/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/bazarr/screenshots/screenshot2.png
sources:
- https://github.com/home-operations/containers/tree/main/apps/bazarr
- https://github.com/morpheus65535/bazarr
title: Bazarr
train: community
version: 1.3.1
