app_version: RELEASE.2026-02-07T07-43-34Z
capabilities: []
categories:
- storage
changelog_url: ''
date_added: '2026-01-12'
description: The Object Store for AI Data Infrastructure
home: https://www.min.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
keywords:
- storage
- object-storage
- S3
lib_version: 2.2.1
lib_version_hash: 243ae7b0656699f970d2816925f27ff4b8e7984bdefc0fa4d4363261f8348c57
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: aistor
run_as_context:
- description: Container [aistor] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://quay.io/repository/minio/aistor/minio
- https://docs.min.io/enterprise/aistor-object-store/installation/container/install/
title: AIStor
train: stable
version: 1.1.0
