app_version: v0.7.6
capabilities: []
categories:
- productivity
changelog_url: https://github.com/TomBursch/kitchenowl/releases
date_added: '2025-06-26'
description: KitchenOwl is a self-hosted grocery list and recipe manager. The backend
  is made with Flask and the frontend with Flutter. Easily add items to your shopping
  list before you go shopping. You can also create recipes and add items based on
  what you want to cook.
home: https://kitchenowl.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/kitchenowl/icons/icon.png
keywords:
- grocery list
- recipe manager
- shopping list
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: kitchenowl
run_as_context:
- description: Container [kitchenowl] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/TomBursch/kitchenowl
- https://hub.docker.com/r/tombursch/kitchenowl
title: KitchenOwl
train: community
version: 1.2.1
