app_version: v0.30.1
capabilities: []
categories:
- media
changelog_url: https://github.com/stashapp/stash/releases
date_added: '2025-06-17'
description: An organizer for your NSFW materials, written in Go.
home: https://stashapp.cc/
host_mounts: []
icon: https://media.sys.truenas.net/apps/stash/icons/icon.png
keywords:
- media
- series
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: stash
run_as_context:
- description: Container [stash] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://hub.docker.com/r/stashapp/stash
- https://github.com/stashapp/stash
title: Stash
train: community
version: 1.1.1
