app_version: 2.0.120
capabilities:
- description: RDT Client is able to change file ownership arbitrarily
  name: CHOWN
- description: RDT Client is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: RDT Client is able to bypass permission checks for file operations
  name: FOWNER
- description: RDT Client is able to change group ID of processes
  name: SETGID
- description: RDT Client is able to change user ID of processes
  name: SETUID
categories:
- media
changelog_url: https://github.com/rogerfar/rdt-client/releases
date_added: '2025-08-27'
description: Real-Debrid Client Proxy
home: https://github.com/rogerfar/rdt-client
host_mounts: []
icon: https://media.sys.truenas.net/apps/rdt-client/icons/icon.svg
keywords:
- media
- ebooks
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rdt-client
run_as_context:
- description: Container [rdt-client] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/rogerfar/rdt-client
title: RDT Client
train: community
version: 1.1.1
