app_version: v3.3.1
capabilities:
- description: Zoraxy is able to perform network administration tasks
  name: NET_ADMIN
- description: Zoraxy is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- networking
changelog_url: https://github.com/tobychui/zoraxy/releases
date_added: '2025-09-05'
description: A general purpose HTTP reverse proxy and forwarding tool.
home: https://zoraxy.aroz.org/
host_mounts:
- description: Network device
  host_path: /dev/net/tun
icon: https://media.sys.truenas.net/apps/zoraxy/icons/icon.svg
keywords:
- proxy
- reverse-proxy
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zoraxy
run_as_context:
- description: Container [zoraxy] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/tobychui/zoraxy
- https://github.com/tobychui/zoraxy/blob/main/docker/README.md
- https://hub.docker.com/r/zoraxydocker/zoraxy
title: Zoraxy
train: community
version: 1.1.2
