app_version: 2026.2.22
capabilities: []
categories:
- ai
changelog_url: https://github.com/openclaw/openclaw/releases
date_added: '2026-02-25'
description: OpenClaw is a personal AI assistant you run on your own devices.
home: https://openclaw.ai/
host_mounts: []
icon: https://media.sys.truenas.net/apps/openclaw/icons/icon.svg
keywords:
- ai
- assistant
- automation
lib_version: 2.2.4
lib_version_hash: eb77489cd9bdce82d347b6ceb30805b58be7838a7048c52dde2bc486b5eeabcd
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: openclaw
run_as_context:
- description: Container [openclaw] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/openclaw/openclaw
title: OpenClaw
train: community
version: 1.0.0
